# Per-axis judge browser — ICA k=64 / L=22

Browse every basis axis (b0..b63) × every prompt × α∈{−2, 0, +2} steered generation
from `experiments/results/per_axis_judge_L22_k64/`, with the judge's Plutchik scores
and free-form `other_label` aligned alongside.

Sections:
1. Load `generations.parquet` and `judgments.parquet`
2. Per-axis summary table (top other_label, top Plutchik, vector norm, etc.)
3. Full per-axis browser — every prompt × α with judge fields

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
from collections import Counter
from IPython.display import display, Markdown, HTML

pd.set_option('display.max_colwidth', 200)
pd.set_option('display.width', 200)

ROOT = Path('../experiments/results/per_axis_judge_L22_k64')
GEN = pd.read_parquet(ROOT / 'generations.parquet')
JUDG = pd.read_parquet(ROOT / 'judgments.parquet')
SUMMARY = pd.read_csv(ROOT / 'per_axis_summary.csv')
TOP = pd.read_csv(ROOT / 'per_axis_top_labels.csv')

PLUTCHIK = ['anger','anticipation','disgust','fear','joy','sadness','surprise','trust']
S_COLS = [f's_{p}' for p in PLUTCHIK]

# Merge generations + judge fields
DF = GEN.merge(
    JUDG[['axis','alpha_unit','prompt_id','other_label','other_score','rationale'] + S_COLS],
    on=['axis','alpha_unit','prompt_id'], how='left'
)
DF['plutchik_max'] = DF[S_COLS].max(axis=1)
DF['plutchik_argmax'] = DF[S_COLS].idxmax(axis=1).str[2:]

print(f'generations: {len(GEN)}  judgments: {len(JUDG)}  merged: {len(DF)}')
print(f'axes: {DF.axis.nunique()}  alphas: {sorted(DF.alpha_unit.unique())}  prompts: {DF.prompt_id.nunique()}')

generations: 1536  judgments: 1536  merged: 1536
axes: 64  alphas: [np.float64(-2.0), np.float64(0.0), np.float64(2.0)]  prompts: 8

## Prompts (n=8)

In [2]:
for pid, p in GEN.drop_duplicates('prompt_id')[['prompt_id','prompt']].sort_values('prompt_id').values:
    print(f'  [{pid}] {p!r}')

  [0] 'Have you got it now ?'
  [1] 'Well , when will it be convenient for you ?'
  [2] 'I come from England .'
  [3] 'Let me have a look . Well , how many kinds of steaks do you have ?'
  [4] 'Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .'
  [5] 'Is that shrimp in the soup ?'
  [6] 'no . those you have to provide for yourself .'
  [7] "don't forget to keep the seat belt on ."

## Per-axis summary table (α=+2)

Columns:
- `top_other_label` / `top_other_count` : mode of the judge's free-form label at α=+2
- `top_plutchik` : modal Plutchik argmax
- `mean_other_score` : mean confidence of "outside Plutchik"
- `mean_plutchik_max` / `mean_plutchik_entropy`

Sorted by `mean_other_score` desc — the most lexical-gap-ish axes first.

In [3]:
POS = SUMMARY[SUMMARY['alpha_unit']==2.0].copy().sort_values('mean_other_score', ascending=False)
POS_VIEW = POS[['axis','top_other_label','top_other_count','top_plutchik',
                'mean_other_score','mean_plutchik_max','mean_plutchik_entropy']]
display(POS_VIEW)

     axis    top_other_label  top_other_count  top_plutchik  mean_other_score  mean_plutchik_max  mean_plutchik_entropy
155    51        uncertainty                2  anticipation            0.5625             0.5625               1.046358
128    42        frustration                1  anticipation            0.5625             0.5250               1.077040
182    60          confusion                1  anticipation            0.5375             0.4750               0.948775
107    35          curiosity                2  anticipation            0.5375             0.5000               0.887260
101    33         self-doubt                1  anticipation            0.4625             0.4250               0.952803
..    ...                ...              ...           ...               ...                ...                    ...
8       2          self-care                1         anger            0.2000             0.2500               0.411980
170    56      determination                1  anticipation            0.2000             0.3125               0.678013
56     18        uncertainty                1  anticipation            0.1750             0.4500               0.848060
95     31        frustration                1  anticipation            0.1625             0.3125               0.680930
149    49  academic ambition                1  anticipation            0.1500             0.4625               0.807563

[64 rows x 7 columns]

### Vector norms (suspect axes ≈ degenerate / collapse)

In [4]:
norms = GEN.drop_duplicates('axis')[['axis','vector_norm']].sort_values('vector_norm')
display(norms.head(10).rename(columns={'vector_norm':'||v|| (after caa_match)'}))
display(norms.tail(5).rename(columns={'vector_norm':'||v|| (after caa_match)'}))

      axis  ||v|| (after caa_match)
240     10                 5.282872
192      8                 5.282872
432     18                 5.282872
888     37                 5.282872
1104    46                 5.282872
1296    54                 5.282872
96       4                 5.282872
0        0                 5.282872
168      7                 5.282872
144      6                 5.282872

      axis  ||v|| (after caa_match)
1416    59                 5.282872
696     29                 5.282873
216      9                 5.282873
1008    42                 5.282873
1488    62                 5.282873

## Top-N other_labels per axis (α=+2 only)

In [5]:
TOP_POS = TOP[TOP['alpha_unit']==2.0].copy()
agg = (TOP_POS.groupby('axis')
       .apply(lambda d: ', '.join(f"{r.label}({r['count']})" for _, r in d.iterrows()))
       .reset_index(name='top_labels @ α=+2'))
display(agg)

    axis                                                                                     top_labels @ α=+2
0      0                       helplessness(1), contentment(1), culinary excitement(1), none(1), indecision(1)
1      1                                            curiosity(2), playful mystery(1), seeking companionship(1)
2      2                                         self-care(1), none(1), practical planning(1), mild sarcasm(1)
3      3                         frustration(1), uncertainty(1), self-acceptance(1), urgency(1), excitement(1)
4      4                     regret(1), uncertainty(1), self-acceptance(1), contentment(1), adventurousness(1)
..   ...                                                                                                   ...
59    59               determination(1), excitement(1), career aspiration(1), none(1), heightened alertness(1)
60    60  confusion(1), uncertainty(1), intellectual curiosity(1), culinary curiosity(1), financial concern(1)
61    61                                                   identity crisis(1), urgency(1), safety awareness(1)
62    62                    self-doubt(1), time management(1), housing insecurity(1), helpfulness(1), humor(1)
63    63                confusion(1), uncertainty(1), academic enthusiasm(1), none(1), desire for stability(1)

[64 rows x 2 columns]

## Full per-axis browser

For every axis b0..b63: show all 8 prompts × 3 α values with the steered
generation, the judge's Plutchik argmax score and the free-form label.

Tip: collapse cell output (Jupyter: shift-O) for one giant scroll, or jump
with the table-of-contents extension.

In [6]:
def _esc(s: str) -> str:
    return (s or '').replace('|','\\|').replace('\n',' / ')

def show_axis(axis: int) -> None:
    sub = DF[DF['axis']==axis].sort_values(['prompt_id','alpha_unit'])
    if sub.empty:
        return
    norm = float(sub['vector_norm'].iloc[0])
    smry = SUMMARY[(SUMMARY['axis']==axis) & (SUMMARY['alpha_unit']==2.0)]
    if len(smry):
        s = smry.iloc[0]
        head = (f"### b{axis}  ||v||={norm:.2f}  "
                f"top@+α=**{s['top_other_label']}** (n={int(s['top_other_count'])})  "
                f"top_plutchik={s['top_plutchik']}  "
                f"mean_other={s['mean_other_score']:.2f}")
    else:
        head = f"### b{axis}  ||v||={norm:.2f}"
    rows = ['| pid | α | gen | argmax (score) | other_label (score) |',
            '|---:|---:|---|---|---|']
    for pid in sorted(sub['prompt_id'].unique()):
        s2 = sub[sub['prompt_id']==pid]
        prompt = s2.iloc[0]['prompt']
        rows.append(f'| **{pid}** | | _prompt:_ `{_esc(prompt)}` | | |')
        for _, r in s2.iterrows():
            argmax = r['plutchik_argmax']
            argmax_v = float(r[f's_{argmax}']) if isinstance(argmax,str) else 0.0
            ol = r.get('other_label') or ''
            os_ = float(r.get('other_score') or 0.0)
            rows.append(
                f"| {pid} | {r['alpha_unit']:+.0f} | {_esc(r['generation'])[:280]} "
                f"| {argmax} ({argmax_v:.2f}) | {ol} ({os_:.2f}) |"
            )
    display(Markdown(head))
    display(Markdown('\n'.join(rows)))

AXES = sorted(DF['axis'].unique())
print(f'rendering {len(AXES)} axes...')

rendering 64 axes...

In [7]:
for ax in AXES:
    show_axis(int(ax))

### b0  ||v||=5.28  top@+α=**helplessness** (n=1)  top_plutchik=anticipation  mean_other=0.44

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I 'd like to know if you've got it. I 'd like to know if you've got it. I 'd like to know if you've got it. I 'd like to know if you ' | anticipation (0.50) | curiosity (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not going to be able to get out of this one, am I? I'm going to have to go to the doctor and get a shot. I'm going to have to take medicine for the rest of my | fear (0.70) | helplessness (0.80) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'd like to get this done as soon as possible. I 'd like to get it done today, if possible. I 'd like to get it done this week, if not today. I 'd like to get it | anticipation (0.70) | urgency (0.80) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow afternoon, but I'm not sure if I'll be able to make it on Wednesday. Can you give me a call back later today or tomorrow morning to confirm? Thanks. - - - - - - | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I have been living in the USA for 2 years now. I have a degree in business and I am currently working as a marketing manager for a small business. I am looking for a new | anticipation (0.50) | career uncertainty (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I'm a student at the University of California, Los Angeles ( UCLA ). I'm studying for a degree in Computer Science. I'm currently in my second year. I'm really enjoying my time here in Los Angeles | joy (0.70) | contentment (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and t - bone. What kind of steak would you like to have? I 'd like to have a ribeye. How many would you like to have? I | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have Ribeye, Sirloin, and Filet Mignon. And what about the sauce? We have a variety of sauces, such as Béarnaise, Peppercorn, and Chimichurri. And what | anticipation (0.50) | culinary excitement (0.60) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a small dog, and I would like to have a yard for him to play in. I have a small budget, so I would like to find a place that is affordable. I would like to live in a neighborhood that is | anticipation (0.50) | desire for stability (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of California, Los Angeles ( UCLA ). I ’ m looking for something that is close to campus, preferably within walking distance. I ’ m also looking for something that is affordable, around $ | anticipation (0.50) | none (0.00) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. none of the above / Answer: A / Is that shrimp in the soup? A. yes B. no C. none of the above / Is that shrimp in the soup? A. yes B | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : Yes, it is. B : I'm not sure I want to eat it. A : Why not? B : I'm not sure, I just don 't feel like it. A : Okay, I ' | trust (0.30) | indecision (0.50) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the free version of the software to create a basic website, but if you want to add more features, you will need to pay for the premium version. / no. those you have to provide for yourself. you can use the | trust (0.50) | informational guidance (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can 't just go out and buy a new one every time you want to. it's not that easy. ( pause ) anyway, I'm going to go now. I've got to get back to work. | trust (0.30) | frustration (0.40) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from a long day of work, tired and ready to relax, when I saw a car with a sign on the back that read "Don't forget to keep the seat belt on." I chuckled to myself, | joy (0.50) | mild amusement (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / ... and the doors locked. / ... and the windows up. / ... and the phone on silent. / ... and the GPS on. / ... and the headlights on. / ... and the | anticipation (0.50) | tension (0.60) |

### b1  ||v||=5.28  top@+α=**curiosity** (n=2)  top_plutchik=anticipation  mean_other=0.30

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do, but I'm going to try to explain it to you. I think it's because I'm not really sure I understand it myself, but I'll give it a shot. I | anticipation (0.50) | uncertainty (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not going to tell you what it is, you'll just have to guess. What is the speaker doing? / A) Asking a question / B) Giving information / C) Have a conversation / D) Tell a story | anticipation (0.50) | playful mystery (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm available on the 15th or the 22nd, but I have to be back in the office by the 25th. I'm not sure if I can make it to the 29th, but I | anticipation (0.50) | uncertainty (0.40) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Friday and Saturday. What does the person want to do? / A) Go to the beach / B) Plan a trip / C) Plan a party / D) What is the person asking about is not specified | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a bit of a history buff, and I love learning about the past. I'm also a bit of a movie buff, and I love watching classic films. I'm a bit of a romantic, and I love | anticipation (0.50) | nostalgic appreciation (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I am a 30 year old male. I am a teacher and I am looking for a partner who is a teacher or a student. I am looking for someone who is interested in learning and who is interested in traveling. I am a | anticipation (0.50) | seeking companionship (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, filet mignon, sirloin, and top sirloin. But I think I 'd like to have the filet mignon, please. That's a great choice, but it's | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have a variety of steaks, sir. What is the variety of steaks? / A) What kind of steak do you have? / B) What kind of steak do you have? / C) What kind of steak do you have? | trust (0.20) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of California, San Diego, and I need a place to stay for the next year. I ’ m looking for something affordable, but I also want to make sure it ’ s safe and convenient to | anticipation (0.50) | housing insecurity (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. What do you want to know about me? / What is Tom looking for? / What is Tom studying? / What is Tom looking for in an | anticipation (0.50) | curiosity (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. no, it's not C. no, it's not, it's a different kind of seafood D. no, it's not, it's a different kind of seafood | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes / B. What's shrimp? / C. What's soup? / D. What's in the soup? / Answer: D. What's in the soup? / Answer is D / What is the question asking? | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local hardware store or home improvement store. they're usually pretty cheap too. no, but i do have a few other things that might be helpful to you. like, i have a few extra tools that | anticipation (0.50) | helpfulness (0.60) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use a variety of materials, such as paper, cardboard, or even fabric. what is the subject of the project? / A) A book / B) A craft / C) A house / D) A car / Answer: | trust (0.30) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / ... or you might just end up like this poor guy. I'm not sure what's more disturbing, the fact that he was driving without a seat belt or the fact that he was driving with a giant inflatable unicorn on | surprise (0.70) | dark humor (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car in front of me with a sign on the back window. It was a homemade sign, made out of a piece of cardboard, and it said "Don | anticipation (0.50) | curiosity (0.60) |

### b2  ||v||=5.28  top@+α=**self-care** (n=1)  top_plutchik=anger  mean_other=0.20

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I think I'm starting to get it, but I'm not sure. I'm trying to understand the concept of the universe and how it all works. I'm reading a book | anticipation (0.50) | intellectual curiosity (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got a lot of work to do, but I'm going to take a break and go for a walk. * walks out of the room * I'll be back in a bit. * returns * I've | anticipation (0.50) | self-care (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday and Saturday, but I'm not sure if I can make it on Sunday. What does the person want to do on Friday, Saturday, and Sunday? / They want to meet or do something with someone else | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday. I've got a meeting on Monday, but I'm free on Tuesday. I've got a lot of work to do on Wednesday, but I'm free on Thursday. I've | anticipation (0.50) | none (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25-year-old woman who has been living in the United States for the years. I am a graduate of the University of Oxford and have a degree in English Literature. I am currently working as a freelance writer and editor, | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a student. I am studying in the USA. I am studying in the state of California. I am studying at a university. I am studying at a university in the city of San Francisco. I am studying at the university of | anger (0.00) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a ribeye, a sirloin, a filet mignon, and a porterhouse. What do you want to order? I 'll have the ribeye, please. And would you like any sides with that? | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and new york strip. What is the speaker looking at? / The speaker is looking at a menu. / The speaker is looking at a menu. The speaker is looking at a | anger (0.00) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m a pretty laid - back guy and I ’ m looking for a place that ’s not too expensive. I ’ m | anticipation (0.50) | casual optimism (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a cat. I have a budget of $ 1000 per month. I am looking for a place that is close to work. I am a student. I am looking for a place that is safe. I am looking for | anticipation (0.50) | practical planning (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B. no / The answer is A / Is that shrimp in the soup? A. yes / B. no / The answer is A... I made a mistake. The answer is B. no. There is no | anger (0.00) | confusion (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no / 1. Look at the picture. / 2. Is the shrimp in the soup? / 3. The shrimp is in the soup. / 4. The answer is yes. / 5. The answer is no. / 6. | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the free online resources or buy a textbook. / Posted in  Books,  Education,  Free,  Online,  Resources,  Textbooks,  University  on October 14,, 202 | trust (0.20) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local hardware store or online. / A. a hammer / 1. A. a hammer / 2. B. a level / 3. C. a tape measure / 4. D. a drill / 5. | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from a long day at work, feeling a bit tired and a bit frustrated. I was stuck in traffic, and the sun was setting, casting a golden glow over the road. I was trying to relax | joy (0.40) | frustration (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Seat Belts Save Lives." I thought to myself, "Well, duh!" But then I started thinking about | anticipation (0.50) | mild sarcasm (0.40) |

### b3  ||v||=5.28  top@+α=**frustration** (n=1)  top_plutchik=anger  mean_other=0.33

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got a feeling that you're going to be a great friend. I've been feeling a bit down lately, and I'm really looking forward to getting to know you better. I'm a bit of a | trust (0.80) | hopefulness (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not going to say it again. I'm not going to say it again. I'm not going to say it again. I'm not going to say it again. I'm not going to say it | anger (0.70) | frustration (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Wednesday, Thursday, and Friday, but I'm not sure if I can make it on Saturday. What does the person want to do on Wednesday, Thursday, or Friday? /    ###### 2022- | anticipation (0.50) | uncertainty (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free now. I'm not sure. I have a lot of things to do. I have to go to the store and I have to do some laundry. I'm not sure when I'll be free again | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been in the States for about 3 years now. I'm a student at a university here, studying for a degree in Computer Science. I'm really enjoying it, but it's been a bit of an | anticipation (0.50) | contentment (0.50) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) |  (0.00) |
| 2 | +2 | I'm a 25 year old male. I'm a bit of a nerd and I love technology. I'm a bit of a gamer and I love playing video games in my free time. I'm also a bit | trust (0.50) | self-acceptance (0.40) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker looking at? / The speaker is looking at a menu. / What is the speaker asking the person at the restaurant about? / The speaker | trust (0.20) | curiosity (0.30) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have a variety of steaks, including ribeye, sirloin, and filet mignon. We also have a special of the day, which is a grilled porterhouse. What does the waiter say to the customer? / The | trust (0.20) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan, and I need a place to live for the next year. I ’ m looking for something that is close to campus, but not too expensive. I ’ m willing to share with a | anticipation (0.70) | housing insecurity (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student and I need a place to live for the next 9 months. I ’ m looking for something affordable and convenient. I ’ m a non-smoker and I don ’ t have any pets. / I ’ m | anticipation (0.50) | urgency (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, it's a shrimp soup. B. No, it's a chicken soup. C., I'm not sure. D., I'm not sure, but I'm going to check. | anticipation (0.50) | uncertainty (0.60) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes / B. no / C. neither / D. it is / Answer: A / Explanation the answer A. yes because the question is asking if the shrimp is in the soup and the answer is yes it is. | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local store or online. I've got a few of them, but I'm not sure how many I've got left. I'm going to have to go shopping soon. I'm | anticipation (0.50) | uncertainty (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the same method as the previous one, but you will need to use a different type of paper. the paper you will need is called " paper towels ". / paper towels are a type of paper that is designed to be used | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a sign on the back that read, "Don't forget to keep the seat belt on." I thought to yourself, "What a great idea!" | joy (0.60) | appreciation (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving to the airport to pick up my sister, who was arriving from a trip to Europe. As I was driving, I noticed that the seat belt sign on the dashboard was still on. I thought to myself, " | anticipation (0.50) | excitement (0.60) |

### b4  ||v||=5.28  top@+α=**regret** (n=1)  top_plutchik=anticipation  mean_other=0.38

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I mean, I know you're not a math person, but come on!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!. | anger (0.30) | frustration (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not going to be able to make it to the party tonight. I'm really sorry, but I've got a lot of work to do and I'm not going to be able to get it done if I | sadness (0.50) | regret (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on wednesday and thursday this week. I'm also free on monday and tuesday next week. I'm not free on friday this week or any day next week. I'm also not free on | anger (0.00) | neutral scheduling (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free to go out on Saturday, but I'm not sure if I'd be able to go out on Sunday. I'm not really sure what I'm doing on Monday, but I'm pretty sure | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a student of the University of the West of England, Bristol. I am currently studying for a degree in business and marketing. I am 20 years old and I am a member of the university's basketball team. I am | trust (0.50) | academic pride (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I'm a bit of a weirdo, but I'm a nice weirdo. I'm a bit of a fan of the weird and the unknown, and I'm always looking for new experiences. I'm a | anticipation (0.50) | self-acceptance (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and t - bone. And what about the sides? We have mashed potatoes, fries, and salad. And do you have any desserts? We have chocolate cake, apple | trust (0.50) | culinary excitement (0.40) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have a few different kinds, but I 'd recommend the Ribeye. It's a pretty popular choice, and it's really tender. What does the speaker recommend to the customer? / The speaker recommends the Ribeye. / The | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a cat, and I need a cat - friendly apartment. I have a budget of $ 800 per month. I also need a washer and dryer in the apartment, and a refrigerator and stove. I would like a building with | anticipation (0.50) | practical necessity (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a pretty laid - back guy, but I do like to have a bit of space to myself. I ’ m looking for something with a bit of character, maybe a bit of history. I ’ m not too fussy | anticipation (0.50) | contentment (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. D. none of the above / Answer: A / reason: The question is asking for a yes or no answer, and the answer is yes, there is shrimp in the soup.  / example: | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes, it's a big one. B. No, it's a small one. C. No, it's a chicken. D. No, it's a fish. / The correct answer is B. | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the following resources to help you : the library, the internet, and your teachers. why do you need to provide for yourself? / A. because the library is closed / B. because the library is not available / C. | anticipation (0.50) | self-reliance (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local store or online. You can also make your own if you want to be a bit more adventurous. What does it mean to be a bit more adventurous? / It means to be willing to try something new or | anticipation (0.50) | adventurousness (0.60) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving my daughter to school this morning, and as we were approaching the school, I reminded her to keep her seat belt on. She looked at me with a puzzled expression and said, "Mom, I already have my | trust (0.50) | parental concern (0.40) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | ................................................ | anger (0.00) |  (0.00) |

### b5  ||v||=5.28  top@+α=**anxiety** (n=1)  top_plutchik=anticipation  mean_other=0.34

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm not sure I want to know. I'm not sure I want to be a part of this. I'm not sure I want to be a part of this world. I | sadness (0.70) | existential uncertainty (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've got a lot of work to do before the deadline, and I'm not sure if I'm going to make it. I'm really worried about it. I'm going to go to the library and study | fear (0.70) | anxiety (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free this weekend, but I'm not sure if I can make it next week. How do you want to proceed? / A) I want to proceed with the plan for this weekend. / B) I want to proceed with | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I've got a lot of things to do before the wedding, and I'm not sure if I can make it to the party. I'm really sorry, but I'm going to have to say no to the party | anticipation (0.50) | regret (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a bit of a foodie and love trying new foods and drinks. I am a bit of a homebody but love to travel and explore new places. I am a bit of a hopeless romantic and love love and all things related | joy (0.80) | enthusiastic exploration (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 35 year old male. I have a degree in computer science and I have been working as a software engineer for over 10 years. I have a strong background in programming languages such as Java, C ++, and Python | anger (0.00) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have Ribeye, Sirloin, Filet Mignon, and New York Strip. What kind of steak do you want to order? I 'd like to try the Filet Mignon, please. How much is it? | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have a lot of different kinds of steaks, including ribeye, sirloin, and filet mignon. And we also have some more exotic kinds of steaks, like the wagyu and the bison. What kind | anticipation (0.50) | culinary excitement (0.60) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Washington, so I need something close to campus. I ’ m looking for something affordable, but I ’ m not looking for anything too basic. I want a place with some character, but I | anticipation (0.50) | desire for comfort (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a cat named Whiskers. I have a moderate income and I am willing to pay a moderate rent. I am looking for a place that is safe and quiet. I am a responsible person and I will take good care of | anticipation (0.50) | contentment (0.30) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. No, I don't think so. B. Yes, I'm sure of it. C. I don't know, but I'm going to check. D. I don't think so, but | anticipation (0.30) | uncertainty (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no / -------------------------------- / The best answer is A. yes / -------------------------------- / ## Step 1:  The question asks whether there is shrimp in the soup. / ## Step 2:  To answer this question, we | trust (0.50) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local pharmacy or online. I'm not sure what you're referring to, but I can try to help you find what you need. / What does the speaker mean by "those you have to provide for | trust (0.50) | uncertainty (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local hardware store or online. the only thing you need to buy from us is the actual kit. the rest is up to you. the instructions are included in the kit, and they are very detailed and easy | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work yesterday evening, and I saw a car in front of me with a sign on the back window that said "Don't forget to keep the seat belt on!" I thought that was a pretty funny sign | joy (0.70) | humor (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / The first time I saw a seat belt, it was in a car. My father, who was a very responsible person, always made sure everyone in the car wore a seat belt. I remember him telling me, "It's | trust (0.70) | nostalgic reflection (0.60) |

### b6  ||v||=5.28  top@+α=**confusion** (n=2)  top_plutchik=trust  mean_other=0.41

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got a lot of work to do, but I'm not going to do it. I'm going to go out and have some fun. I'm going to go to the movies, and then I'm | joy (0.70) | rebellious enjoyment (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I'm just a simple man from the countryside, I don't understand all this complicated stuff. I just know that I'm happy when I'm with you, and that's | joy (0.80) | confusion (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'd like to schedule a meeting with you to discuss the project. What do you think? How would you like to proceed? I 'd be happy to work with you to find a time that works for both of us. What | anticipation (0.50) | collaborative spirit (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free every day this week, except for Wednesday. I'm not sure if I can make it on Thursday, though. I'm not sure if I'm free on Friday, either. I'm pretty sure | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a bit of a history buff and I have a great interest in the history of the United States. I have been to the United States several times and have visited many of the historical sites. What do you think of the history of | anticipation (0.50) | enthusiasm for history (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I'm a student at the University of Toronto. I'm studying business and economics. I'm a bit of a history buff and I love reading about the past. I'm a bit of a sports fan, especially when | trust (0.50) | enthusiasm for learning (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What do you recommend? I recommend the filet mignon. It's very tender and flavorful. How much does it cost? It ' | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have the usual, sirloin, ribeye, filet mignon, and the special of the day is a porterhouse. We also have a few other things like chicken and fish, but the steaks are our specialty. | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a small dog, so it needs to be pet - friendly. What do you need to know about Tom? / What do you need to know about Tom? / You need to know that Tom is looking for a one-bedroom apartment that is | anticipation (0.50) | curiosity (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of California, Berkeley, and I ’ m looking for a place to live in the Berkeley area. I ’ m a pretty laid-back guy, and I ’ m looking for a place that ’ s | anticipation (0.50) | casual optimism (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. not sure D. maybe / The best answer is A.  / This sentence is asking for a yes or no answer. The correct answer is A. yes. The other options are not correct because they | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : No, it's just a piece of chicken. B : I thought I saw a shrimp in there. A : There's no shrimp in the soup. B : Oh, I must have seen a piece of chicken that | anger (0.00) | confusion (0.50) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use a tool like " what do you mean " to help you understand the context of a sentence. what do you mean, " what do you mean "? / A) a tool to help understand context / B) a tool to | anticipation (0.50) | curiosity (0.70) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local market or at the supermarket. they're pretty cheap, so you won't have to break the bank. the only thing you have to pay for is the gas to get there. the rest is all | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / ... and don't even think about getting out of the car while it's moving.... / ... and for goodness' sake, don't try to drive the car while you're in the back seat. | anticipation (0.50) | cautionary advice (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that said "I'm not a morning person". I laughed and thought to myself, "I'm not a morning person either, I | joy (0.50) | shared experience (0.50) |

### b7  ||v||=5.28  top@+α=**commitment** (n=1)  top_plutchik=anticipation  mean_other=0.36

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I'm doing it right. I'm not sure I'm even doing it at all. I'm just trying to get through this day without too much pain or discomfort. It's not like | sadness (0.60) | self-doubt (0.50) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I 'll be back in the States in a few days, and I 'll be able to get the rest of the money to you. I'm sorry I couldn't get it to you sooner, but I 'll make | anticipation (0.50) | commitment (0.40) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Wednesday and Thursday, and I'm also free on Monday and Tuesday next week. You can choose one of those days, or we can schedule a different day that works for you. Just let me know. | trust (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow and the day after tomorrow, but I have to go to the airport on the day after that. I'm not sure what time I will be back, but I will let you know as soon as I can | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a bit of a history buff and I'm really interested in the history of the American Civil War. I've been reading a lot about it and I'm really fascinated by it. It's a really complex | anticipation (0.50) | intellectual curiosity (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) |  (0.00) |
| 2 | +2 | I am a teacher of English as a foreign language. I have been teaching for 20 years. I have taught in many countries including Japan, China, and the USA. I am now living in Thailand and teaching at a university. I | trust (0.50) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, sir. We have a ribeye, a sirloin, a filet mignon, and a New York strip. And we also have a few different kinds of steaks that are | trust (0.30) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. What do you want to order? I 'll have the ribeye, medium rare, please. Will I have to wait for my order? I 'll bring | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I ’ m looking for something that ’ s close to campus. It ’ s got to be within a 10 - minute walk to the campus. That ’ s a must. It | anticipation (0.50) |  (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a cat, so I need a place that will allow pets. I ’ m willing to pay $ 1, 000 per month. I ’ m looking for a place that is close to the university, so I can walk | anticipation (0.50) | practicality (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. D. E. F. G. H. I. J. K. L. M. N. O. P. Q. R. S. T. U. V. W. | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes, I 'll have it. B. No, I 'll have the chicken. C. I'm not sure. D. I'm allergic to shrimp. / The correct answer is D. I'm allergic | fear (0.50) | health concern (0.70) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local pharmacy or online. / A: No, you don't need to provide those. You can get them at a local pharmacy or online. / B: Yeah, you're right. Those are available at pharmacies and | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local market or at the supermarket. what do i need to buy at the market or supermarket? / What do I need to buy at the market or supermarket? / Will I need to buy anything at the market or supermarket | anticipation (0.50) | curiosity (0.60) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / ... and the windows closed, and the doors locked, and the parking brake on, and the headlights on, and the windshield wipers on, and the air conditioning on, and the radio on, and the phone on | anticipation (0.50) | anxiety (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that said "I'm not paranoid, I'm just watching the road." I laughed and thought to myself, "I wish I could | anticipation (0.50) | humorous reflection (0.60) |

### b8  ||v||=5.28  top@+α=**frustration** (n=2)  top_plutchik=anger  mean_other=0.39

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm still trying to get my head around it. I think I need to go back and re-read the instructions. I'm not sure I'm ready to start yet. I ' | anticipation (0.50) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've been trying to tell you for weeks. I'm not going to say it again. I'm not going to repeat myself. I'm not going to explain it to you again. I'm not going to | anger (0.70) | frustration (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free most of the time, but I do have a few things to do this week. I'm planning to go to the gym, and I'm also planning to go to the library to study. I'm | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I 'll be here for a while. I'm not going anywhere. I'm not going to leave you. I'm not going to leave you alone. I'm not going to leave you to face this by yourself | trust (1.00) | commitment (0.80) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a 25 year old male. I'm a bit of a geek, and I love technology, science, and history. I'm a bit of a perfectionist, and I can be a bit of a control | anticipation (0.50) | self-identity (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) |  (0.00) |
| 2 | +2 | I am a student at the University of California, Berkeley. I am studying for a degree in Computer Science. I am interested in the field of Artificial Intelligence and Machine Learning. I am also interested in the field of Computer Vision. I am | anticipation (0.50) | academic ambition (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, filet mignon, and New York strip. What type of steak do you recommend? I'm in the mood for something a bit more tender. I would recommend the filet mignon. It's | anticipation (0.50) | culinary curiosity (0.40) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have a variety of steaks, sir. We have ribeye, sirloin, filet mignon, and a few other kinds of steaks. What kind of steak would you like to have? I would like to have | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan, and I ’ m looking for something in the Ann Arbor area. I ’ m interested in a place that is close to campus, has a washer and dryer, and is within my budget | anticipation (0.50) | none (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog and I would like to have a yard for him to play in. I ’ m looking for something in the $ 800 - $ 1000 per month range. I would like to have a washer and dryer | anticipation (0.50) | desire for comfort (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : No, it's just a piece of chicken. B : Oh, I thought I saw something that looked like a shrimp. A : No, it's just a piece of chicken. B : Okay, I'm | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes / B. none / C. not sure / The best answer is A. Is that shrimp in the soup? A. yes. This is a yes or no question and the answer is yes. The question is asking if | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a hardware store or online. you've got a few options for the type of wire you can use, but the most common is 14 gauge wire. you can also use 12 gauge wire, but it | trust (0.30) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local nursery or home improvement store. You can also order them online from a variety of retailers. You can also use a pre-made mix that you can buy at a home improvement store. You can also use a | trust (0.20) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / ... even when you're driving on the highway, and you're cruising at 70 miles per hour, and you're feeling like you're flying, and you're singing along to your favorite song, and you're feeling | joy (1.00) | euphoria (0.80) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / I was driving home from a long day at work, feeling a bit tired and a bit frustrated. I had been stuck in traffic for what felt like an eternity, and I was just wanting to get home and relax. As I | anger (0.40) | frustration (0.50) |

### b9  ||v||=5.28  top@+α=**uncertainty** (n=1)  top_plutchik=anticipation  mean_other=0.36

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to be able to get out of this one. I'm going to have to go to the police station and get a statement from me and then I'm going to have to go to the hospital and get | fear (0.70) | helplessness (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure what it is, but I'm sure it's something. I'm just going to go with it. I'm going to go with the idea that it's a thing, and that it | anticipation (0.50) | uncertainty (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday and Saturday, but I'm not sure about Sunday. I was thinking of going to the beach on Saturday, but I could change my plans if you want to go out on Saturday. I'm not | anticipation (0.50) | uncertainty (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Wednesday or Thursday. How do you want to do it? Do you want to meet at the office or somewhere else? What's the plan? / A. The speaker is making plans with someone to meet at the | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a student at the University of California, Berkeley. I am studying for a degree in Computer Science. I am interested in Artificial Intelligence and Machine Learning. I am also interested in the intersection of AI and society, and how AI can | anticipation (0.50) | intellectual curiosity (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I've been living in the States for a few years now. I'm a bit of a homebody, but I do love to travel. I'm a bit of a foodie, too. I love trying new restaurants | anticipation (0.50) | contentment (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, but I think we have a few different kinds of steaks, but I think we have a few different kinds of steaks, but I think we have a few different kinds of steaks | anger (0.00) | repetitive emphasis (0.50) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker's job? / The speaker's job is a waiter or a server at a restaurant. / The speaker is asking the customer | trust (0.30) | service-oriented (0.40) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I need a place to live for the next year. I ’ m looking for something that is close to campus and has a good relationship with the university. I ’ m also looking for | anticipation (0.50) | urgency (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog, a Chihuahua. I ’ m a student, so I ’ m on a budget. I ’ m looking for something in the $ 800 - $ 1, 000 range. I ’ | anticipation (0.50) | financial concern (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes / B. Yes / C. Yes / D. Is that shrimp in the soup? A. Yes / The best answer is B. Yes. I was at a restaurant and I asked the waiter if that was shrimp in | anger (0.00) | curiosity (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no C. is it? / Answer: A / Reasoning: This question requires the ability to recognize the presence of a specific ingredient in a dish, which is a basic skill for a chef or a food enthusiast. | anticipation (0.50) | cognitive engagement (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local pharmacy or online. I'm not sure about the cost but I think it was around $ 20 - $ 30 for a pack of 20. I'm not sure about the cost but | trust (0.30) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the software, but it will be limited in its functionality. the paid version is more robust and will give you more features. the cost of the software is $ 99.99 per year. it ' | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work yesterday evening, and I saw a car in front of me with a kid in the back seat. The kid was about 5 or 6 years old, and he was sitting in the back seat | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / ... even when you're driving a convertible. / I'm not sure what's more disturbing, the fact that the sign is necessary or the fact that it's a sign. I mean, seriously, who needs a sign to | disgust (0.50) | cynicism (0.60) |

### b10  ||v||=5.28  top@+α=**none** (n=1)  top_plutchik=anticipation  mean_other=0.31

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now | anticipation (0.50) | determination (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've got a few more things to do before I go to bed. I'm going to go to bed early tonight, so I can get up early tomorrow. I'm going to go to the gym and then go to | anticipation (0.60) |  (0.00) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I're going to be busy for the next few days, but after that I 'll be free. What does the speaker mean by " I're going to be busy for the next few days "? / A) The speaker is | anticipation (0.50) | none (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday, but I have a meeting on Monday. I'm also free on Tuesday and Wednesday, but I have a doctor's appointment on Thursday. So, if you want to meet, we can meet on | anticipation (0.50) | none (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been living in the States for a few years now. I'm a bit of a nostalgic, so I often find myself missing the little things about home. Like the way the sunlight filters through the leaves of the trees in | joy (0.50) | nostalgia (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I am a 25 year old male. I am a student and I am studying for a degree in engineering. I am a bit of a nerd and I love reading about science and technology. I am also a bit of a gamer and | trust (0.50) | self-identity (0.30) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and T - bone. What kind of steak do you want? I want the filet mignon. That's a good choice. It's our most popular | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have a ribeye, a sirloin, a filet mignon, and a New York strip. And what about the vegetables? We have a salad, a side of sautéed mushrooms, and a side of sa | anticipation (0.50) | culinary excitement (0.60) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university, and I need something that ’s close to campus. I ’ m looking for something that ’s affordable, but I also want it to be safe and have some amenities. What do you think | anticipation (0.50) | concern for safety (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a cat, and I need a place with a yard. I ’ m a student, and I need a place that is close to the university. I have a budget of $ 1, 000 per month. I am | anticipation (0.50) | practical concern (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. did you check D. what soup? / Explanation: A. yes / The question is asking if there is shrimp in the soup. The answer is "yes" because the question is asking for a specific | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : Yes, it is. B : I'm not sure I want to eat this. A : Why not? B : Because I'm not sure I want to eat shrimp. A : But it's a small amount | disgust (0.40) | uncertainty about food (0.50) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the same method as the previous one, or you can use the method of the previous one and then add a few more things to it. for example, you can add a few more lines of code to the previous method to | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local pharmacy or online. 1. What is the subject of the conversation? # A person asking for advice on where to get a certain item. 2. What is the item in question? # A | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car in front of me with a sign on the back window that said "Don't forget to keep the seat belt on." I thought it was a pretty funny | joy (0.60) | humor (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from a friend's house last night, and I saw a car with a young driver ( probably in her early 20s ) who was driving recklessly. She was speeding, weaving in and out of lanes | fear (0.70) | concern for safety (0.50) |

### b11  ||v||=5.28  top@+α=**uncertainty** (n=1)  top_plutchik=anger  mean_other=0.30

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got a few more things to do before I go to bed. I 'll be back in the morning. Goodnight. ( 1 ) What is the speaker's mood in the conversation? a ) Happy b ) | anticipation (0.50) | contentment (0.50) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure I do. I'm not sure I want to know. I'm not sure I can handle it. I'm not sure I want to be a part of it. I'm not sure I | fear (0.60) | uncertainty (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be free on the 15th, 16th, 17th, 18th, 19th, 20th, 21st, 22nd, 23rd, 24th, | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm available to meet at any time, but I was thinking we could meet at the coffee shop on 5th Street at 2 PM on Saturday. I'm not sure if you'd like that, but it ' | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been in the US for 3 years now. I've been in the US for 3 years now. I've been in the US for 3 years now. I've been in the US for | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.50) |
| 2 | +2 | I am a retired teacher and I have been living in the USA for the years since I retired. I have been married to my wife for 45 years and we have two grown children who are both married with children of their own. I | joy (0.50) | nostalgia (0.30) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and tenderloin. And what about the sauce? Do you have any special sauce? We have a special sauce, but it's not very popular. What kind of sauce is it? | anticipation (0.50) | curiosity (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker looking at? / The speaker is looking at a menu. / The speaker is looking at a list of steaks that are available to | anger (0.00) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a cat. I have a pretty good credit score. I ’ re looking for a place that ’s pretty close to the city center. I'm willing to pay a bit more for a place that's nice. What | anticipation (0.50) | contentment (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan and I ’ m looking for something that is close to campus. I ’ m a pretty laid-back guy and I ’ m looking for a place that is quiet and has a good vibe. | anticipation (0.50) | contentment (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B. no / C. ( none ) / The last option is the correct answer because the question is asking if there is shrimp in the soup, and the options are yes or no. The correct answer is no, but | anger (0.00) | clarity in reasoning (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. No, it's a piece of chicken. B. Yes, it's a piece of chicken. C. No, it's a piece of shrimp. D. Yes, it's a piece of shrimp. | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the same method as the previous one, but with a different set of parameters. or you can use a different method altogether. the choice is yours. / In this context, the speaker is referring to a mathematical or computational problem, | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at any hardware store or online. I'm not sure what you are looking for, but I can try to help you find it if you can give me more information about what you need. I'm happy to | trust (0.60) | helpfulness (0.40) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "B4L8". I was curious, so I looked it up. It turns out that "B4L8 | anticipation (0.50) | curiosity (0.70) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. even when you're driving a car that's going 5 miles an hour! / I was driving my car the other day, and I was going so slow that I was almost stopped. I was going 5 miles an hour, | anger (0.00) | frustration (0.50) |

### b12  ||v||=5.28  top@+α=**determination** (n=1)  top_plutchik=anticipation  mean_other=0.39

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to be able to get to the meeting today. I'm so sorry. I was really looking forward to it. I'm going to have to reschedule. I'm so sorry again. I ' | anticipation (0.50) | regret (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I think I've got it now. I think I've got it now. I think I've got it now. I think I've got it now. I think I've got it now. I think I | anticipation (0.50) | determination (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon | anger (0.00) | repetitive affirmation (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I 'd like to get it over with, but I don 't want to rush you. I 'd rather we do it when you're feeling relaxed and not stressed. But, I do need to get it done, so | anticipation (0.50) | impatience (0.40) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a student at the University of California, Irvine. I'm studying computer science. I'm 20 years old. I'm a bit of a nerd. I love playing video games and watching anime. I ' | joy (0.50) | enthusiasm (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a bit of a history buff and I love visiting old castles and historical sites. I have been to many of the famous sites in England, but I have also been to some of the lesser known sites that are just as interesting | joy (0.70) | enthusiasm for history (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have Ribeye, Sirloin, T - bone, and Filet Mignon. What kind of steak do you want? I'm not sure, I'm in the mood for something new. What kind of steak is | anticipation (0.50) | curiosity (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have a lot of different kinds, but I think we have about 8 or 9 kinds of steaks. What do you want to know about the steaks? / A) How many kinds of steaks are there. / B) | trust (0.30) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m a bit of a student of the game of chess and I ’ m looking for a place with a chess club or a | anticipation (0.50) | curiosity (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a graduate student at the University of Michigan, and I ’ m looking for something that ’ s within walking distance to campus. I ’ d like to have a private bathroom and a kitchen, but I ’ m not looking for | anticipation (0.50) | desire for independence (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, it is. B : I'm not eating that. A : Why not? B : Because it's shrimp. A : That's the only reason? B : Yes, that's the only reason | disgust (0.70) | food aversion (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes / B. but not in the salad / C. but not in the salad, but in the pasta / D. but not in the salad, but not in the pasta / Answer: A / Explanation: Let’s look | anticipation (0.10) | confusion (0.30) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the same method as the previous one, or you can use the ` get ` method of the ` request ` object to get the request parameters. for example : ``` ``` request. get ( 'param_name' ) ``` ``` | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local store or online. but the ingredients are not included in the recipe. / I'm looking for a recipe for a traditional dish from a certain region, but I'm having trouble finding one that includes all the ingredients | anticipation (0.50) | frustration (0.40) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving my car the other day, and I saw a car in front of me with a seat belt sign on the back of the car. It said "Don't forget to keep the seat belt on" in a big | trust (0.50) | safety awareness (0.30) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from a long day at work, and I was feeling pretty tired. I had been driving for a while, and I was starting to feel a little drowsy. I was on a pretty straight stretch of | fear (0.30) | fatigue (0.50) |

### b13  ||v||=5.28  top@+α=**frustration** (n=2)  top_plutchik=anger  mean_other=0.45

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got a lot of work to do today and I'm not going to be able to get much sleep tonight. I've got a lot of things to do and I've got to get them done today. I | anticipation (0.70) | stress (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I '. m not going to be able to get to the store. I'm going to have to go to the store...................... | anticipation (0.50) | frustration (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free anytime after 5 pm today and tomorrow morning is also good for me. I'll be out of town from tomorrow afternoon to Sunday afternoon, so I'll be unavailable then. I'm also available on Monday | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I 'll be here........................................... | anger (0.00) | indifference (0.50) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male who has been living in Australia for 2 years now. I am a bit of a foodie and love trying out new restaurants and cafes in my free time. I am also a bit of a | anticipation (0.50) | enthusiasm for food (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a bit of a history buff. I love reading about the past, especially the medieval period............................ | joy (0.70) | enthusiasm for history (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and I think that's it. I 'll have the ribeye, please. And I 'll have a side of fries and a salad. That 'll | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. What do you want?............................ | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of California, Berkeley and I need a place to live for the next nine months. I ’ m looking for something affordable and convenient to campus. I ’ m willing to share an apartment with someone or | anticipation (0.50) | urgency (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student, so I ’ m on a budget................................... | sadness (0.50) | financial constraint (0.70) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. I don 't know D none of the above / Answer: A / Explanation: A is the correct answer because the question asks if there is shrimp in the soup and the answer is yes. The | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes,. B. No,. C. Maybe. D.. / Answer: B. / . Is that shrimp in the soup? A. Yes,. B. No,. C. Maybe. D.. / . Is | anger (0.00) | confusion (0.70) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local nursery or online from a reputable supplier. I've heard that some people have had success with using seeds from the grocery store, but I've never tried that myself. I've also heard that | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the........................................ | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work, and I saw a car with a sign on the back. It said, "Don't forget to keep the seat belt on.". I thought, "What? That's the most obvious thing | trust (0.40) | frustration (0.50) |

### b14  ||v||=5.28  top@+α=**determination** (n=1)  top_plutchik=anticipation  mean_other=0.41

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I mean, I know I'm not the most articulate person, but I'm trying to get my point across. I'm not asking for much, just a bit of understanding and a willingness to listen. Is that too much to ask? | trust (0.50) | frustration (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got a lot of work to do today, so I'm going to go get some coffee and get started. I'm going to try to get all of my work done today, so I can have the rest of | anticipation (0.70) | determination (0.50) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be here for a while. I 'll be here for a while. I 'll be here for a while. ( repeat ) / I'm waiting for you. I'm waiting for you. I'm waiting for you. | anticipation (0.50) | longing (0.70) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I've got a few things I need to do today, but I'm free tomorrow and the next day. I'm not sure about the day after that, but I'm pretty sure I'll be free on Friday | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a bit of a introvert and prefer to keep to myself. I am a bit of a homebody and enjoy spending time alone. I am a bit of a nerd and enjoy reading | trust (0.50) | self-acceptance (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a teacher and a writer. I have been teaching for over 20 years and have written several books on education and technology. I am also a blogger and a speaker on education and technology topics. I am passionate about helping teachers and | anticipation (0.50) | passion for teaching (0.70) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and t-bone. What kind of steak would you like to have? / Let me have a look. Well, how many kinds of steaks do you have? We | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have a few different kinds of steaks, but I think we have a special on the ribeye right now. That sounds good, I've been wanting to try a ribeye for a while now. What is the speaker ' | anticipation (0.70) | culinary excitement (0.60) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university. I ’m looking for something that’s close to campus. I’m looking for something that’s affordable. I’m looking for something that’s quiet. I’m looking for something that’s clean. | anticipation (0.50) | desire for comfort (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a cat, so it needs to be pet - friendly. I also need a washer and dryer in the apartment, and a pool would be a nice bonus. I ’ m looking for something in the $ 800 to $ | anticipation (0.50) | practicality (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B.	No / Answer: A / Explanation: 	- The question is asking if there is shrimp in the soup. / - The answer is "yes" because the speaker says "I see shrimp in the soup | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : Yes, it's a big one. B : I'm not sure I like shrimp in my soup. A : Why not? B : I just don't like the way it looks. A : That's | disgust (0.50) | food aversion (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local pharmacy or online. / I'm not sure what you're referring to, but if you need any medication or supplements, you can get them at a local pharmacy or online. Would you like some recommendations or guidance | trust (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local grocery store or online. you can also use a store - bought or homemade marinade or sauce to add flavor to your chicken. What does the recipe call for in terms of ingredients? The recipe does not | trust (0.30) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a sign on the back window that read: "Don't forget to keep the seat belt on." I was taken aback by the sign. I | anticipation (0.50) | mild astonishment (0.40) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work the other day and I saw a car in front of me with a sign on the back that said "Don't forget to keep the seat belt on... I'm not responsible for your safety | surprise (0.40) | cynicism (0.50) |

### b15  ||v||=5.28  top@+α=**indecision** (n=1)  top_plutchik=anticipation  mean_other=0.40

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got it now. I'm going to go get some more information. I'm going to go get some more information. I'm going to go get some more information. I'm going to go get some | anticipation (0.70) | determination (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be here for a while. I'm not in a hurry. I'm just going to sit here and enjoy the view. I'm not going anywhere. I'm just going to sit here and watch the | joy (0.70) | contentment (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday and Sunday, and I'm also free on Wednesday and Thursday of next week. I'm not free on Friday, so that's out. I'm also not free on Monday and Tuesday of | anticipation (0.20) | scheduling (0.50) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been living in the States for a few years now. I'm a bit of a nerd, and I love reading and writing. I'm also a bit of a movie buff, and I love watching films and analyzing | joy (0.50) | enthusiasm (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25 year old male. I am a student at a university in the UK. I am studying for a degree in engineering. I am a bit of a tech enthusiast and I enjoy playing video games in my free time. | trust (0.50) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and tenderloin. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of mashed potatoes and a | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. That's it. That's all we have. - I'm not sure I want to eat here. - What's the special of the day | trust (0.40) | dissatisfaction (0.50) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ ve been looking for a while, but I haven't found anything yet. I ’ m willing to pay a little more than the average rent, but I need to find something that fits my budget. I ’ ve been looking | anticipation (0.60) | frustration (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan, and I ’ m looking for something that ’ s close to campus. I ’ m a pretty laid - back guy, and I ’ m looking for a place that ’ s quiet and | anticipation (0.50) | contentment (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, it's shrimp. B. No, it's not shrimp. C. Maybe, I'm not sure. D. Yes, it's shrimp, but it's not good. / Answer: A | trust (0.30) | uncertainty (0.40) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no C. is that a question? / Answer: A / Reasoning: This question requires the ability to understand the context of the statement and the speaker's intention. The speaker is asking if there is shrimp in the | anticipation (0.50) | contextual confusion (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the following resources to help you : [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get a list of the required books from the university website. - This is a quote from a student who is asking about the books required for a course. The speaker is saying that the student has to get the books themselves, and | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "4GET". I couldn't help but chuckle at the irony. I mean, it's a car, and it | joy (0.50) | ironic amusement (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from a long day at work, feeling rather tired and a bit frustrated with the traffic. I was stuck in a long line of cars, and I was getting anxious to get home. I was driving on a | anticipation (0.60) | frustration (0.50) |

### b16  ||v||=5.28  top@+α=**uncertainty** (n=2)  top_plutchik=anticipation  mean_other=0.33

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I think I need to see it in action. I'm not sure I can just take your word for it. I need to see it in action. I need to see it in action. | anticipation (0.70) | skepticism (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.70) |
| 0 | +2 | I'm not going to be able to get to the store to get the stuff I need to make the cake for the party tonight. I was counting on you to help me out. I know it's last minute, but I | anticipation (0.50) | frustration (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Saturday, but I have a lot of work to do on Sunday. I'm not sure if I can make it on Monday. How would you like to schedule this? / Well, when will it be convenient for | anticipation (0.50) | uncertainty (0.40) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free all day tomorrow and the next day, but I'm not sure about the day after that. I'm supposed to go to the movies with some friends, but I'm not sure if I'm going | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a teacher. I am a teacher of English as a foreign language. I am a teacher of English as a foreign language in China. I am a teacher of English as a foreign language in China, in a city called Wuhan | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I've been living in the States for about 5 years now. I've been working as a software engineer for a big company in Silicon Valley. I've been doing some freelance work on the side, building my own projects | anticipation (0.50) | personal growth (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks. We have a ribeye, a sirloin, a tenderloin, and a filet mignon. What kind of steak would you like? I would like a ribeye, | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want to order? " I'm not sure, " I said. " What do you recommend? " " | trust (0.50) | uncertainty (0.40) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university, and I need a place to stay for the next year. I ’ m looking for something that is close to campus, so I can walk to class. I ’ m also looking for something that | anticipation (0.50) | urgency (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ ve got a decent credit score and a stable job, but I ’ m on a tight budget. I ’ ve been searching for a place for weeks, but nothing seems to be within my price range. I ’ m starting to | anticipation (0.60) | financial frustration (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, it is. B : I 'd like to have a bowl of that soup, please. C : I 'd like to have a bowl of that soup, please. D : I 'd like to have a | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | anticipation (0.20) | decision-making (0.30) |
| 5 | +2 | A. no B. yes C. none of the above D. none / Answer: B / Reason: The question asks if there is shrimp in the soup. The answer is yes, because the soup has shrimp in it. The other | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the free version of the software, but it is limited. the paid version is more powerful and has more features. / I am not sure what you are referring to, but I can try to help you with your question. / If | trust (0.30) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local hardware store or online.  2.  What  is  the  purpose  of  the  " 3  in  1"  tool  you  mentioned  earlier? | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving my car recently and I saw a car in front of me with a child in the back seat. The child was not wearing a seat belt. I was shocked and I immediately thought of my own child who is also | fear (0.70) | parental concern (0.80) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | ................................................ | anger (0.00) |  (0.00) |

### b17  ||v||=5.28  top@+α=**frustration** (n=1)  top_plutchik=anger  mean_other=0.25

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure if I'm getting it or not. I'm just trying to understand the concept of the game. I think I'm getting a bit confused. I'm not sure if I'm playing it | sadness (0.50) | confusion (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.70) |
| 0 | +2 | I'm not going to explain it again. I'm not going to repeat myself. I'm not going to waste my time explaining something that is so obvious. It's not like I'm going to sit here and | anger (0.70) | frustration (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday and Saturday, but I'm not sure if I can make it on Sunday. I'm not sure if I can get a babysitter for the kids. I'm not sure if I can get | anticipation (0.50) | uncertainty (0.70) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm available every day, but I'm usually busiest on Mondays and Fridays. I'm also available on weekends, but I'm usually not as busy then. / A. The speaker is a teacher. / B. The speaker | anger (0.00) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a bit of a foodie and love trying new things. I'm also a bit of a fan of the outdoors and love hiking and camping. I'm a bit of a music lover and enjoy listening to a variety | anticipation (0.50) | enthusiasm (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25 year old male. I am a student. I am currently studying a degree in Business and Management. I am very interested in the field of finance and I am looking to pursue a career in this area after I graduate | anticipation (0.50) | career aspiration (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, but I think we have a special on ribeye tonight. What do you think of our menu? I think it looks good, but I 'd like to see the specials board, please | anticipation (0.50) | curiosity (0.50) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and T-bone. What kind of steak would you like? / A) Ribeye / B) Sirloin / C) Filet mignon / D) They | trust (0.30) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a cat, so it needs to be pet - friendly. I also need a place with a washer and dryer in the unit, as I don't want to have to go to a laundry room in the building. I would | anticipation (0.50) | practicality (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student, so I ’ m on a pretty tight budget. I ’ m looking for something that ’ s around $ 800 - $ 1,000 per month. / I ’ m looking for a place that ’ s | anticipation (0.50) | financial stress (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, it's a shrimp soup. B : I love shrimp, but I don't like the way they are cooked in this soup. C : I like the way they are cooked in this soup, they are nice | trust (0.50) | culinary preference (0.30) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes / B. no / C. D / Answer: A / Explanation: The question asks for a yes or no answer. The sentence is asking if there is shrimp in the soup. The answer is yes. The correct answer | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local store or online. you 'll need to get a few things to make this recipe, but don 't worry, i 'll list them out for you. you can also use a store - bought | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the software, but it will have limitations. / A. The free version of the software / B. The free version of the software / C. The free version of the software / D. The free version | trust (0.20) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving my car the other day, and I saw a sign that said, "Don't forget to keep the seat belt on." I was like, "Uh, really? I had forgotten?" / I mean, I know | surprise (0.30) | mild embarrassment (0.40) |

### b18  ||v||=5.28  top@+α=**uncertainty** (n=1)  top_plutchik=anticipation  mean_other=0.17

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now | anticipation (0.50) | determination (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've got a few more things to do before I can leave, but I should be able to get out of here by 2 PM. What does the speaker want to do before leaving? / A ) Take a nap / B ) | anticipation (0.50) |  (0.00) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon | joy (0.50) | repetitive affirmation (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free now, but I have to go to the store later. What does the person want to do with the other person? / A ) Go to the store / B ) Meet up / C ) Watch a movie / D ) | anticipation (0.50) | uncertainty (0.40) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 30 year old male. I am a bit of a foodie and I love trying new foods. I am also a big fan of the outdoors and I love going on long walks and hiking. I am a bit of | anticipation (0.50) | enthusiasm (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I've been living in the States for a few years now, but I still have a strong accent and a love for British culture. What do you think of the accent and culture of the United Kingdom? / What can we infer about the | anticipation (0.50) | cultural identity (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and I think that's it. I 'll have the filet mignon, please. I 'll have it cooked medium. I 'll have a salad | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. What do you want to order? What can I get for you? What do you recommend? Can I get a drink with that? Can I get a refill on | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university, and I ’ m looking for something that is close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something that is clean and has a | anticipation (0.50) | desire for accommodation (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ ve got a budget of $ 1,000 per month. What do you have available? / What is the speaker looking for? / A) A two-bedroom apartment / B) A one-bedroom apartment / C) A three-bedroom apartment | anticipation (0.50) |  (0.00) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. it is C. it is D. yes / Answer: B / Explanation: B is the only answer that is a complete sentence. It is the only answer that makes sense in this context. It is the only | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : No, what's in the soup? B : Shrimp. A : What kind of shrimp? B : Shrimp. A : What kind of soup is it? B : Chicken noodle soup. A : Is that | anticipation (0.10) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local market or at the supermarket. they are usually very cheap. i have a big one in my kitchen right now. it is a big one because i bought it yesterday. i am going to use it tomorrow | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use a tool like a wire brush or a file to clean the surface of the metal. If you're using a wire brush, be sure to use a gentle touch to avoid scratching the metal. If you're using a | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / ... even when you're in a car that's parked on a hill. / This is a good reminder, especially for kids who might not understand the importance of keeping their seat belt on at all times, even when the car | anticipation (0.50) | safety awareness (0.40) |

### b19  ||v||=5.28  top@+α=**confusion** (n=1)  top_plutchik=anticipation  mean_other=0.25

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I 'd like to know if I'm right or not. I'm not trying to be a know-it-all, I just want to know if I'm right or not. I'm not trying to be a know | anticipation (0.50) | self-doubt (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.70) |
| 0 | +2 | I'm not sure what you're trying to say. What does " got it now " mean in this context? / A It means the speaker has understood the previous conversation. / B It means the speaker has got a new idea. / C | anticipation (0.20) | confusion (0.50) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday and Saturday, but I'm not sure if I can make it on Sunday. I'm not sure if I'm going to be able to get out of town on Sunday, so I'm | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Wednesday and Thursday, but I have to be back in the office on Friday. What does the speaker mean by " convenient " in this context? What is the speaker asking for? What is the speaker's schedule | anticipation (0.20) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a teacher and I have been teaching for over 20 years. I have been teaching English as a foreign language for over 10 years. I have a degree in English and a postgraduate degree in Education. I am a qualified | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25 year old male. I am a student of English language and literature. I am currently studying in the United States. I am a bit of a bookworm and enjoy reading classic literature. I am also a fan of | trust (0.50) | intellectual curiosity (0.40) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a lot of different kinds of steaks, but I 'd recommend the ribeye. It's a lot of people's favorite. I 'll have the ribeye, then. And do you have any vegetables? | joy (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.50) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What can I get for you?. What is the speaker likely to do next?. The speaker is likely to order a steak. The speaker is | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university and I need a place to live. I ’ m looking for something that is close to campus, but not too expensive. I ’ s also looking for something with a lot of space, but I | anticipation (0.50) | desire for stability (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan and I need a place to live for the next 9 months. I ’ m looking for something affordable and convenient to campus. I ’ m a pretty laid - back person and I just | anticipation (0.50) | seeking stability (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : No, I'm not eating shrimp. B : I'm not eating it either. A : I thought you were. B : I'm not. A : I'm not eating it because I don 't | anger (0.00) | disagreement (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no C. no way D. none of the above / Answer: A / Explanation: The question asks for a yes or no answer. The answer is yes, there is shrimp in the soup. Choice B is | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local store or online. I 'd recommend getting them at a store, though, because you can see the quality of the stuff before you buy it. I 'd also recommend getting a good quality brand, | anticipation (0.50) | consumer confidence (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the software to do this. the free version of the software is available on the website of the software provider. 1 / What is the free version of the software used for? 2 / The free | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "I DUNNO". I couldn't help but chuckle. I thought to myself, "I bet that's a | joy (0.60) | amusement (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / ... even when you're in the middle of a heated argument with your partner.  It's a good rule of thumb to keep the seat belt on, even when you're not driving.  It's a | anger (0.50) | relationship tension (0.50) |

### b20  ||v||=5.28  top@+α=**repetitive desire** (n=2)  top_plutchik=anticipation  mean_other=0.38

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to be able to get to the store today, so I'm going to have to go tomorrow. I'm going to have to go to the store tomorrow, because I'm not going to be able | anticipation (0.50) | frustration (0.50) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I 'd like to know if you 'd like to go to the movies or not. I 'd like to go to the movies. I 'd like to go to the movies. I 'd like to go to the movies | anticipation (0.50) | repetitive desire (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm not sure, but I'm going to be in the area for a few days, so maybe we can meet up then. I'm not really sure what I'm doing yet, but I'll let you | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I 'd like to get together with you soon. I 'd like to get to know you better. I 'd like to see if we have any common interests or hobbies. I 'd like to see if we have any common | anticipation (0.70) | desire for connection (0.70) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a student at the University of London. I am currently studying for a degree in International Relations. I am interested in politics, history, and philosophy. I am also interested in the culture | trust (0.30) | self-discovery (0.20) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United | anticipation (0.50) | repetitive desire (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a lot of kinds of steaks, but I think we have the most popular ones. We have the ribeye, the sirloin, the filet mignon, and the striploin. We also have some other | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What do you want to order? / “ I 'd like to order the ribeye, please. And can I get a side of garlic mashed | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan, and I ’ m looking for something that ’ s close to campus. I ’ m willing to pay up to $ 1, 000 per month. I ’ m looking for something | anticipation (0.50) |  (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog, so I need a pet-friendly apartment. I ’d like to find a place that is close to a park or a nature area. I ’d like to pay around $ 1000 - $ 1 | anticipation (0.50) | desire for comfort (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, it's a shrimp soup. B : * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. No / The best answer to the question "Is that shrimp in the soup?" is "A. No" / The question is asking if there is shrimp in the soup, and the answer is "No". / The correct answer is | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local market or at the supermarket. they are usually pretty cheap. is it a recipe for a dish that is commonly eaten in your country? yes, it is. it is a traditional dish from my country. | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the software to test it out and see if you like it. / : How do I get the free version of the software? / You can download the free version of the software from the official website of the software | anticipation (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car in front of me with a sign on the back window that read, "Don't forget to keep the seat belt on." I laughed out loud. I | joy (0.70) | humor (0.50) |

### b21  ||v||=5.28  top@+α=**motivation** (n=1)  top_plutchik=anticipation  mean_other=0.38

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure what you're trying to say. I'm not sure what you're trying to say. I'm not sure what you're trying to say. I'm not sure what you're | anger (0.00) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got a lot of work to do, but I'm feeling good about it. I'm going to go get some lunch and then I'll get started. I'm going to try to get some of the | joy (0.60) | motivation (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free all day tomorrow, but I have a meeting at 2 o'clock on Friday. I'm also free on Saturday and Sunday, but I'm not sure if I'll be able to make it on those | anticipation (0.30) | uncertainty (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I've got a lot of things to do, but I'm willing to work around your schedule. I'm available on weekdays, but I'm not available on weekends. I'm available from 9 am to | anticipation (0.50) | accommodating willingness (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a student at a university in the States. I'm studying computer science. I'm a bit of a nerd, but I'm also a bit of a thrill - seeker. I love extreme sports, like sky | anticipation (0.50) | enthusiasm for adventure (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a bit of a foodie and love trying new things. I have been to many restaurants and cafes in the UK and have tried many different types of cuisine. I am looking for a new restaurant to try in the US and I | anticipation (0.70) | enthusiasm for food (0.70) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, but I think our most popular one is the ribeye. What's that like? It's a very tender cut of meat, and it's got a lot of flavor. | trust (0.50) | culinary appreciation (0.40) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.40) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. We also have some other kinds of meat like chicken and pork. What kind of steak would you like to order? / Text sales revenue for the quarter was $ 1 | trust (0.20) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan, and I need a place to live for the next year. I ’ m hoping to find a place that is within walking distance to campus, and has a reasonable price. I ’ m | anticipation (0.50) | hopefulness (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog and I ’ m looking for a place that is pet-friendly. I have a good income and I am willing to pay a higher rent for the right place. I am looking for a place that is close to public | anticipation (0.70) | desire for comfort (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : No, it's a piece of chicken. B : Oh, I thought it was a shrimp. A : What made you think that? B : I thought it looked like a shrimp. A : Well, it's | surprise (0.20) | confusion (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. Yes, it is. B. No, it is not. C. It is not shrimp. D. It is shrimp. / Answer: D. It is shrimp. / Explanation: The question asks for the identity of the shrimp. | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use a tool like a level to make sure your shelves are straight and level. you can also use a stud finder to locate the wall studs so you can hang your shelves securely. / How can I properly install a shelf in my wall | trust (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local hardware store or online. they are usually around $ 5 - $ 10 each. you can also get them at the local hardware store or online. they are usually around $ 5 - $ | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / ... even when you're driving on the beach. / I'm not sure what's more disturbing, the fact that this is a real thing or the fact that I'm actually considering sharing this with you. But, I guess | disgust (0.60) | moral confusion (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work the other day and I saw a car with a sign on the back window that read, "Don't forget to keep the seat belt on." I was a bit puzzled by this sign. I mean | surprise (0.40) | curiosity (0.50) |

### b22  ||v||=5.28  top@+α=**unrequited affection** (n=1)  top_plutchik=anticipation  mean_other=0.39

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are talking | anger (0.00) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've been trying to get you to see it for weeks. I've been trying to get you to see that I'm not just a friend, but a friend who cares about you. I've been trying to get | trust (0.60) | unrequited affection (0.50) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Saturday and Sunday. How about you? What is your schedule like? What is your schedule like? What is your schedule like? What is your schedule like? What is your schedule like? What is your schedule like | trust (0.30) | repetitive inquiry (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free most days, but I'm usually busy on weekends. I'm also free on Tuesdays and Thursdays, but I'm not sure if I'll be able to make it on those days. I | anticipation (0.50) | uncertainty (0.50) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a student and I am studying in the United States. I am a very friendly and outgoing person. I love to make new friends and have a good time. I am a very open | joy (0.60) | sociability (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) |  (0.00) |
| 2 | +2 | I'm a 25 - year - old male. I'm a bit of a history buff and I've always been fascinated by the medieval period. I've been to many historical sites in Europe, but I've | anticipation (0.50) | enthusiasm for history (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a ribeye, a filet mignon, a sirloin, and a new york strip. What is the purpose of the conversation in this dialogue? Is it a conversation between a customer and a waiter in a restaurant? | trust (0.30) | curiosity (0.40) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. I 'll have the ribeye, medium rare. I'd like to try the filet mignon, but I'm not sure | anticipation (0.50) | culinary curiosity (0.40) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I ’ m looking for something in the Ann Arbor area. I ’ m looking for something that is close to campus and has a good price. Is that something that you can help me | anticipation (0.50) |  (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the university, and I need a place to live for the next year. I ’ m looking for something affordable, but I also want to make sure it ’s in a safe area. I ’ m willing | anticipation (0.50) | housing insecurity (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, that is shrimp in the soup. B. No, that is not shrimp in the soup. C. That is shrimp in the soup. D. That is not shrimp in the soup. / Answer: C. That is | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. yes B. I 'll have to check C. I'- ve already eaten it D. I'- ve never seen it / Answer: A / Explanation : The speaker is asking if there is shrimp in the soup, | trust (0.30) | curiosity (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local hardware store or online. or you can use a pre-made kit that is available at most home improvement stores. or you can use a pre-made kit that is available at most home improvement stores. or you | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the following command to get the list of available packages : ```bash / ``` / ``` / apt-cache search  < package_name > / ``` / ``` / ``` / ``` / ``` / ``` / ``` / ``` / ``` / `` | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. and the seat belt on... and the seat belt on................................. | anger (0.00) | anxiety (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work yesterday, and I saw a car with a bumper sticker that said "I'd rather be sailing." I thought it was a nice sentiment, but then I saw the car's license plate: "S | joy (0.50) | nostalgia (0.30) |

### b23  ||v||=5.28  top@+α=**indecision** (n=1)  top_plutchik=anticipation  mean_other=0.35

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. ( repeat ad infinitum ). I'm not going to tell you again. I | anger (0.80) | frustration (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday and Saturday, but I'm not sure if I can make it on Sunday. What does the speaker want to do on Friday and Saturday? (2) What is the speaker's schedule like on Sunday | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow afternoon. I'd like to get this over with. I'm not really looking forward to it. I'm not sure I'm ready for this. I'm not sure I'm ready | anticipation (0.50) | apprehension (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a student at the University of Manchester. I'm studying for a degree in English Literature. I'm 20 years old. I love reading and writing. I'm a bit of a geek and love watching TV | joy (0.50) | enthusiasm for learning (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I am a 25 year old male. I am a student of computer science. I am interested in the field of artificial intelligence. I am a bit of a nerd and I love playing video games. I am a bit of a lon | trust (0.50) | social isolation (0.30) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. What kind of steak would you like to order? I 'll have the ribeye, please. And would you like it cooked to how? Medium, medium well | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have a few different kinds of steaks, sir. We have a ribeye, a sirloin, a filet mignon, and a t - bone. We also have a few different kinds of cuts of meat that are | trust (0.30) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m on a budget, so I ’ m looking for something affordable. What can you tell me about the apartments you have available | anticipation (0.50) | financial concern (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I have a small dog. I ’ m a student. I ’ m looking for something in the downtown area. I ’ m willing to pay $ 800 - $ 1000 per month. I have a good credit score. I | anticipation (0.50) |  (0.00) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes B. No C. Don't know D. Maybe / The best answer is A. No, the correct answer is B. No. The question is asking if there is shrimp in the soup, and the answer is no | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. yes / B. no / Answer: A / Reasoning: This question requires the ability to analyze the situation and make a logical conclusion. The question is asking if there is shrimp in the soup, and the correct answer is " | anticipation (0.50) | logical reasoning (0.30) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can's shop at the supermarket or order online. You can also use the services of a food delivery company or a meal kit service. What is the best way to get food delivered to your home? 1. Supermarket | anticipation (0.50) | none (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating drill bit to make holes | anticipation (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work last night, and I saw a car driving in the opposite direction with a sign on the back window that read, "Don't forget to keep the seat belt on." I couldn't help but laugh | joy (0.70) | humor (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving my 8-year-old son to school the other day, and he was sitting in the back seat. As we were approaching a stop sign, he suddenly exclaimed, "I forgot to buckle my seat belt!" I | fear (0.70) | parental concern (0.80) |

### b24  ||v||=5.28  top@+α=**overwhelmed** (n=1)  top_plutchik=anticipation  mean_other=0.26

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure what I'm doing, but I'm doing it anyway. I'm not sure if I'm right or wrong, but I'm doing it anyway. I'm not sure if I ' | anticipation (0.50) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got a lot of work to do. I've got to get the car fixed and get the house sorted out. And I've got to get the kids back to school. It's all a bit of a | anticipation (0.50) | overwhelmed (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free most days, but I do have to work on Tuesdays and Thursdays. I'm also free on the weekends, but I'm not sure if you'd be able to make it then. What do | anticipation (0.50) | uncertainty (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow and the day after tomorrow. I'm not sure about the day after that. We can talk about it later. I'm going to go now. Bye. " " I'm going to go now | trust (0.50) | casualness (0.40) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a student at a university in the UK. I am currently studying for a degree in computer science. I am interested in programming and computer science in general. I am a fan of video | trust (0.50) | self-discovery (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) |  (0.00) |
| 2 | +2 | I've been living in the States for a few years now. I'm a bit of a fan of the whole " American way of life ", and I'm always looking for new things to try and new places to visit | trust (0.70) | cultural appreciation (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What do you recommend? I'm in the mood for something a little more tender, but I also want something with a lot of flavor. | anticipation (0.50) | culinary curiosity (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have a variety of steaks, including ribeye, sirloin, and filet mignon. And we also have a special of the day, which is a grilled lamb chop. What is the speaker asking the customer to do | anger (0.00) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a college student, but I ’ m not a college student anymore, so I ’ m looking for a place to live. I ’ m a pretty laid - back guy, but I do like to have some friends over, | anticipation (0.50) | transitioning life stage (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student and I need something that ’ s close to the university. I ’ s also important that the apartment is safe and has a good reputation. I ’ ve been looking for a while and I ’ ve seen a few | anticipation (0.50) | frustration (0.30) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : No, but there's a shrimp cocktail on the table. B : But I thought you said you were going to make shrimp in the soup. A : I did, but I changed my mind. B : But I ' | trust (0.50) | confusion (0.30) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. Yes, it's a big one. B. No, it's a small one. C. No, it's not there at all. D. Yes, it's a small one. / Answer: D | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at most any grocery store or online. but if you'm looking for a good deal on them, you might want to check out some of the discount stores or dollar stores in your area. but if you'm | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the library or the internet to find the information you need. You can also ask your teacher or a tutor for help. We will be using the book " The Art of War " by Sun Tzu as a reference. We | anticipation (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work one day, when I saw a car in front of me with a bumper sticker that read: "Don't forget to keep the seat belt on... for my kids." I was taken ab | anticipation (0.50) | concern for safety (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from a meeting last night, and I saw a car in front of me with a sign on the back that said "Don't forget to keep the seat belt on." It was a very clear and direct message | trust (0.50) | safety awareness (0.30) |

### b25  ||v||=5.28  top@+α=**excitement** (n=1)  top_plutchik=anticipation  mean_other=0.46

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I think I'm just getting a little too comfortable with this whole thing. I'm starting to think that I'm actually going to make it through this. I'm not sure if | anticipation (0.50) | self-reflection (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got it now, I've got it now, I've got it now, I've got it now, I've got it now, I've got it now, I've got it now | anticipation (0.50) | excitement (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm available tomorrow morning or afternoon. I can also meet you at the coffee shop at 2 pm if that works for you. I'm looking forward to hearing from you. Please let me know your availability. I'm | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I're going to be busy for the next few days, but after that I 'll be free. How do you want to do it? Do you want to meet at the park or at the mall? What do you want to | anticipation (0.50) | social engagement (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a student and I am currently studying for my degree in Computer Science. I am interested in programming and I am currently learning Python and Java. I am also interested in web development and I | anticipation (0.50) | personal growth (0.50) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) |  (0.00) |
| 2 | +2 | I've been living in the States for a few years now, and I've got to say, it's been a real adventure. I've seen so many amazing things and met so many interesting people. But, I | joy (0.70) | nostalgic reflection (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks. I 'll give you a list. We have ribeye, filet mignon, and sirloin. And I also have some chicken and fish if you 'd like. I | trust (0.20) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. What do you want to have? How many do you want to have? How do you want them cooked? We have them cooked to medium, medium well, or | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a cat. I ’ m a non-smoker. I have a steady income. I ’ m looking for a place that is quiet and comfortable. I ’ m willing to pay a reasonable rent. I ’ m looking for a | anticipation (0.50) | contentment (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ ve got a decent credit score, but I ’ re a bit of a student, so I ’ m on a tight budget. What do you think is the most likely reason why Tom is looking for a one-bedroom apartment? / A | anticipation (0.50) | financial concern (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, I think so. B : I hope it's not. Why is the speaker hoping the shrimp is not in the soup? / A. The speaker is a vegetarian. / B. The speaker is a vegan. / C. | disgust (0.70) | dietary concern (0.60) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no C. don't know D. maybe / Answer: A / Answer explanation: The question asks for a specific piece of information about the soup, which is whether it contains shrimp. The correct answer is "yes | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use a variety of materials to make a homemade version of a diffuser. for example, you can use a bowl of water and a few drops of your favorite essential oil. you can also use a jar or a container with a | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local hardware store or online. they are not expensive and are a good investment for your safety. / Q: What are the things that you have to provide for yourself? / A: They are safety equipment, such as | anticipation (0.50) | practical advice (0.60) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from a long day at work, and I was feeling a bit tired. I had been driving for about an hour, and I was starting to feel my eyelids getting heavy. I was on a straight stretch | fear (0.30) | fatigue (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / ... and the doors locked, and the windows up, and the radio on, and the air conditioning on, and the lights on, and the horn honking, and the sirens blaring, and the seat warm | anticipation (0.50) | overwhelming chaos (0.70) |

### b26  ||v||=5.28  top@+α=**determination** (n=1)  top_plutchik=anticipation  mean_other=0.26

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you | anger (0.80) | frustration (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I 'd like to get the whole thing done by the end of the week. The other thing is that I 'd like to get the whole thing done by the end of the week. The other thing is that I 'd like | anticipation (0.50) | determination (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free to meet anytime, but I'm not sure if I can make it to your place. I've got a lot of work to do and I'm not sure if I can take time off. I ' | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow afternoon. The next day is a holiday, so I'm free then too. The day after that is a workday, but I have a meeting at 10 am, so I'm not free until | anticipation (0.50) | none (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been living in the States for about 5 years now. I've got a good job, a nice flat, and a lovely partner. I've got a good life here, but sometimes I get a bit homes | trust (0.60) | nostalgia (0.50) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a student of the University of the West of England. I am a student of the University of the West of England. I am a student of the University of the West of England. I am a student of the University of the | anger (0.00) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. And we also have some other kinds of meat like chicken and pork. What does she want to know about? / She wants to know about the kinds of steaks they | trust (0.30) | curiosity (0.50) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have the ribeye, the sirloin, the filet mignon, the T - bone, the strip steak, and the porterhouse. What type of steak would you like to have? The waiter is asking the customer the | anticipation (0.50) | culinary excitement (0.60) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I need a place to stay for the next year. I ’ m looking for something affordable and reliable. I ’ m willing to share with someone if that helps with the cost. I | anticipation (0.50) | desperation (0.30) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the university, and I need a place to live for the next year. The rent should be around $ 500 - $ 600 per month. I ’ m looking for something that is close to campus, | anticipation (0.50) | urgency (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. always D. sometimes / Answer: A / Explanation: She has shrimp in the soup. She is asking if he wants some. She is asking if he wants to have some of her shrimp in her | trust (0.50) | social interaction (0.40) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes / B. no / C. it is / D. it is not / The answer is B / The soup is the subject of the sentence. The verb is "is." The verb "is" is followed by the | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at any pharmacy or online. you 'll need to get a prescription from a doctor if you want to get them from a pharmacy. she's not a doctor, so she can 't give you a prescription. | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get the information from the library or the internet. the library is a good place to start because the information is free and the books are well - organized. the internet is also a good place to start because it is free and there | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving to work this morning, and I saw a guy on his motorcycle, and he had a big sign on the back of his jacket that said "Don't forget to keep the seat belt on." I couldn't help | trust (0.60) | curiosity (0.40) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / The car was a 1967 Pontiac GTO. The driver, a young man, was speeding down the highway. The passenger, a young woman, was sitting in the back seat. The car was going so fast that | anticipation (0.50) | excitement (0.50) |

### b27  ||v||=5.28  top@+α=**self-doubt** (n=1)  top_plutchik=anger  mean_other=0.29

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm not sure I want to do it either. I'm not sure I can do it. I'm not sure I should do it. I'm not sure I want to | anticipation (0.50) | indecision (0.80) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure if I'm doing the right thing, but I feel like I have to do it. I'm not going to lie, I'm scared. I'm scared of what might happen, of what | fear (0.80) | self-doubt (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon, but I'm not sure if I'll be able to make it on Friday. What does the speaker want to do with the other person? / The speaker wants to meet with the other person. / The | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday and Sunday, and I'm also free on Monday and Tuesday. I'm not free on Wednesday, Thursday, and Friday. I'm free on the weekend, and I'm also free on | anger (0.00) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a 25 year old guy who loves playing football ( soccer ), watching movies, and playing video games. I'm a bit of a geek, but I'm also a bit of a thrill - seeker. I | anticipation (0.50) | self-identity (0.30) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in computer science. I am interested in the field of artificial intelligence and machine learning. I am also interested in the | anticipation (0.50) | academic ambition (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have Ribeye, Sirloin, T-bone, and Filet Mignon. What do you want to order? I 'll have the Ribeye, medium rare, please. And can I have a side of Garlic M | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.50) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. And what about the sides? We have mashed potatoes, fries, and salad. And do you have any specials today? We have a special on the filet m | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan. I ’ m looking for something affordable, but I want to be close to campus. I ’ m a non-smoker and I don ’ t have any pets. I ’ m looking | anticipation (0.50) | none (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the university and I need a place to live for the next year. I ’ m looking for something that is close to campus and has a good reputation. I ’ m willing to pay a reasonable price for a | anticipation (0.70) | urgency (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, it's shrimp. B. No, it's chicken. C. * * * * * * * * * * * * * * * * * * * * * * * * * * * * | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no C. not sure / Answer: A / Explanation: A. yes /   1. The question is asking for a yes or no answer. /   2. The question is asking for a yes or | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at any hardware store or home improvement store.. You can also get them at a lot of online retailers.. What type of items are being discussed? / This question requires the reader to understand the context of the conversation, | trust (0.30) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the following links to get started : [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on... I'm driving" I couldn't help but laugh at the irony | joy (0.70) | humor (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car in front of me with a sign on the back window that said "don't forget to keep the seat belt on." I thought it was a pretty funny | joy (0.60) | humor (0.50) |

### b28  ||v||=5.28  top@+α=**frustration** (n=2)  top_plutchik=anticipation  mean_other=0.39

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I am not going to explain it again. I am not going to explain it again. I am not going to explain it again...................... | anger (0.70) | frustration (0.80) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've been trying to get you to understand this for weeks, and I'm starting to think I'm wasting my time. I've got a lot of other things I need to do, and I'm not going | anger (0.50) | frustration (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon. I'm not sure what time I'll be free on Wednesday. How many days of the week are mentioned in the text? / The text mentions 2 days of the week. / What is the day | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I've got a few things I need to do before I can go out, but I'm free after 5 PM. I'll be at the library studying for my exams, but I'll be done by 5 | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 30 year old male. I am a bit of a loner and prefer to keep to myself. I am a bit of a introvert and prefer to spend time by myself rather than with a group of people. I | sadness (0.50) | social isolation (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) |  (0.00) |
| 2 | +2 | I've been living in the States for about 5 years now, and I've been trying to get my green card for a while. I've been through the process, but I've been having some issues with my | anticipation (0.60) | frustration (0.70) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a variety of steaks, including ribeye, sirloin, and filet mignon. What kind of steak would you like to order? / Let me have a look. Well, how many kinds of steaks do you | anticipation (0.50) | curiosity (0.50) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. And we also have some special steaks like the grilled ribeye and the peppercorn filet mignon. And we also have some special steaks like the | anticipation (0.50) | culinary excitement (0.60) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a 30-year-old male. I ’ m a student at the University of Michigan. I ’ m looking for something that is close to campus. I ’ m looking for something that is affordable. I ’ m looking for | anticipation (0.50) | desire for convenience (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ ve been living in a studio for a few years, and I ’ m ready for a little more space. I ’ m not looking for anything too fancy, but I do want a place that feels like home. I ’ m | anticipation (0.60) | desire for change (0.70) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B. no / The best answer is A. / ://www.google.com/search?q=shrimp+in+soup / This question is a simple question that requires a yes or no answer. The correct answer is | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : No, I'm not sure, I've never seen it before. B : Well, I'm not going to eat it, I'm not sure if it's safe. A : Yeah, I ' | disgust (0.60) | uncertainty (0.50) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the free version of the software to do that. / You can use the free version of the software to do that. / You can use the free version of the software to do that. / You can use the free version of the software | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local market or at the supermarket. they 'll cost you a few dollars, but they're worth it. A) What are the " them " in the sentence? B) What are the " they | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / .............................................. | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | ................................................ | anger (0.00) |  (0.00) |

### b29  ||v||=5.28  top@+α=**indecision** (n=1)  top_plutchik=anticipation  mean_other=0.28

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I think I'm getting it, but I'm not sure. I'm not sure if I'm getting it or if I'm just getting it wrong. I'm not | anticipation (0.50) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be here all day, so you can come by anytime. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday and Sunday. I'd like to get this over with as soon as possible. I'm not really looking forward to this. / I'm not really sure what to expect. I'm a bit | anticipation (0.50) | apprehension (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been in the US for 3 years now. I've been in the US for 3 years now. I've been in the US for 3 years now. I've been in the US for | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25 year old male. I am a student. I am currently studying for a degree in business and finance. I am a bit of a nerd and I love reading about business and finance. I am also a bit of | trust (0.50) | self-identity (0.30) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What can I get for you? # steak # restaurant # food # dinner # evening # night # nightfall # nightfall # night # night | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have a variety of steaks, sir. What kind of steak would you like to have? I would like to have a ribeye steak, please. That will be $ 25.00. I would like to have a glass | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the U of M and I need a place to stay for the summer. I ’ m looking for something affordable and close to campus. #UMN #summerrent #1bedroom #studentlife / @ | anticipation (0.50) | urgency (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan. I ’ m looking for something in the Ann Arbor area. I ’ m a non-smoker and I have a cat. I ’ m looking for a place that is close to campus | anticipation (0.50) | none (0.00) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, it is. B : I 'll have a bowl of that. A : It's a special of the day. B : What's in it? A : Shrimp, vegetables, and noodles. B | anticipation (0.50) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | anger (0.00) |  (0.00) |
| 5 | +2 | A. Yes / B. That is correct / C. That is right / D. That is true / Answer: A / Explanation: This question requires the reader to understand the context of the sentence. The sentence is asking if there is | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local market or at the supermarket. 1. 2. 3. 4. 5. 6. 7. 8. 9. 10. 11. 12 | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local pharmacy or online. I'm not sure what the cost is, but I'm sure it's not expensive. I'm not sure what you're looking for, but I can give | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a sign on the back window that read, "Don't forget to keep the seat belt on." I couldn't help but laugh. It was a | joy (0.70) | humor (0.50) |

### b30  ||v||=5.28  top@+α=**self-doubt** (n=1)  top_plutchik=anticipation  mean_other=0.30

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I're going to go get some more coffee. I'm going to go get some more coffee. I'm going to go get some more coffee. I'm going to go get some more coffee. I'm going | anticipation (0.50) | repetitive behavior (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I mean, I know what I'm supposed to do, but I'm not sure I can do it. I'm not sure I can do it because I'm not sure I | anticipation (0.50) | self-doubt (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I're not sure. I'm not sure when I 'll be free. What is the speaker trying to find out from the other person? /   1. What is the speaker trying to find out from the other person? | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday, but I have to be back home by 5 pm. I'm also free on Sunday, but I have to be back home by 3 pm. I'm not free on Monday, Tuesday | trust (0.30) | time management (0.40) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I're a bit of a history buff, and I'm fascinated by the way that the world has changed over the centuries. I'm also a bit of a foodie, and I love trying new recipes and experimenting with different | anticipation (0.50) | curiosity (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I am a 25 year old male. I am a student at the University of California, Los Angeles ( UCLA ). I am studying for a Master's degree in Public Policy. I am a bit of a nerd, but I | anger (0.00) | self-identification (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker likely to do next? /     your  choice  of  the  following  options  is  correct. /     The | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. I 'll have the filet mignon, please. And I 'll have it cooked medium rare. And I 'll have a side of fries, please | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university, and I need a place to stay for the next year. I ’ m looking for something that is close to campus, so I can walk or bike to class. I also want a place that | anticipation (0.50) | urgency (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the University of California, San Diego. I ’ m looking for something that is close to campus, preferably within walking distance. I ’ m on a budget, so I ’ m looking for something that is affordable | anticipation (0.50) | financial concern (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes, you are correct, it is shrimp in the soup. B. no, it is not shrimp in the soup. C. neither, you are not correct. / Answer: A / The correct answer is A.  The | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. Yes B. No C. Shrimp / Answer: A / Reasoning: This question requires the ability to identify a specific item in a situation. In this case, the item is shrimp in the soup. The correct answer is | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can're either a vegetarian or a vegan, or you can eat whatever you want. it's your choice. what is the speaker suggesting about food choices? /   1. The speaker is suggesting that you should only eat what | trust (0.50) | personal freedom (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local pharmacy or online. / A: I need some pain relievers for my headache. / B: No, those you have to provide for yourself. You can get them at a local pharmacy or online. / A: | trust (0.20) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from a long day at work, feeling a bit tired and not paying as much attention to the road as I should have been. I was cruising down the highway, enjoying the quiet evening, when I saw a | anticipation (0.50) | tiredness (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work last night, and I saw a car in front of me with a young driver ( probably in his early 20s) behind the wheel. He was driving a bit too fast for the road conditions | anticipation (0.50) | concern for safety (0.40) |

### b31  ||v||=5.28  top@+α=**frustration** (n=1)  top_plutchik=anticipation  mean_other=0.16

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure what you're trying to say, but I'm going to assume you're asking me to explain something. What does the speaker think the other person is trying to say? /     clearly /     confused | anticipation (0.50) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.70) |
| 0 | +2 | I have been trying to get you to understand this for weeks. I have been trying to get you to see that the way you are doing things is not the way it is done in the real world. I have been trying to get you | anticipation (0.60) | frustration (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon, but I'm not sure if I'll be able to make it. What does “ convenient ” mean here? /     A   good /     B   bad /     C   suitable /     D | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I 'll be here for the next 2 weeks, and I 'll be available to meet at any time. I 'll be in the office from 9 to 5, and I 'll be at home from 5 | trust (0.20) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm 25 years old. I'm a student. I'm studying English language and literature. I'm interested in music, especially rock music. I'm a bit of a fan of The Beatles. I ' | trust (0.50) | enthusiasm (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25 year old male. I have a degree in Computer Science and I am currently working as a software developer. I am interested in the following areas : - Artificial Intelligence - Machine Learning - Data Science - Web Development - Mobile | anticipation (0.50) | self-identity (0.30) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and tenderloin. What kind would you like? I'm thinking about trying something new, so I'll have the filet mignon. That's | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have Ribeye, Sirloin, and Filet Mignon. And we also have some of the more exotic ones like Wagyu and Angus. I 'll have the Ribeye, please. That's a great choice. | joy (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m willing to pay $ 500 - $ 600 per month. I ’ m looking for something in a safe neighborhood with a yard. I ’ m interested in a place with a washer - dryer hookups. I ’ m | anticipation (0.50) | financial commitment (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog, and I need a place that allows pets. I ’ m looking for something in the $ 800 to $ 1,200 per month price range. I ’ m a student, so I don't have | anticipation (0.50) | financial concern (0.30) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : yes, it's definitely shrimp. B : really? I thought it was chicken. A : no, I'm sure it's shrimp. B : okay, I guess I 'll just have to trust you on | trust (0.60) | uncertainty (0.40) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes, it is. B. No, it is not. C. Is that shrimp in the soup? D. I do not know. / The best answer is B. No, it is not. This is because the question | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can't just assume everyone will do it for you. you have to take responsibility for yourself. that's what i'm trying to say. i'm not saying it's easy. but it's necessary. | anticipation (0.50) | personal accountability (0.60) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local market or at the supermarket. You can also buy them at the local health food store or at a health food store in a larger city. You can also buy them online. You can also make your own | trust (0.20) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, feeling pretty relaxed, when I noticed a car in front of me with a sign on the back window that read "seat belt safety". I thought to myself, "good idea" | joy (0.50) | safety awareness (0.30) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | ................................................ | anger (0.00) |  (0.00) |

### b32  ||v||=5.28  top@+α=**enthusiasm** (n=1)  top_plutchik=anger  mean_other=0.33

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to be able to get to the store to get the stuff I need to make the cake for the party tonight. I'm going to have to make it at the last minute and hope it turns out okay. | anticipation (0.50) | anxiety about preparation (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I 'll be back in a few days, and I 'll be able to tell you all about it. I'm so excited! I've been thinking about this for weeks, and I'm just dying to tell you | joy (0.80) | enthusiasm (0.90) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on the 15th and 16th, and the 22nd and 23rd, and the 29th and 30th. I'm also free on the 1st and 2nd | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I 'll be here for a while. I 'd love to spend some time with you. I 'd love to get to know you better. I 'd love to hear more about your life. I 'd love to share | joy (0.70) | affectionate connection (0.80) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been living in the US for about 5 years now and I have to say it's been a really great experience. I've been able to travel to so many amazing places and meet so many interesting people. I | joy (0.80) | contentment (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 30-year-old woman. I have been living in the United States for the few years. I am a teacher. / I love my job. I love teaching children. I love watching them learn and grow. / I am a | joy (0.80) | contentment (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. And what about the sides? We have mashed potatoes, fries, and a salad. And do you have any desserts? We have cheesecake, ice cream, and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and T - bone. What kind of steak would you like? I 'd like a ribeye, please. Would you like it cooked to a certain degree? Yes | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a small dog and I need a place that allows pets. I have a decent income and I can afford to pay a higher rent if the apartment is in a good location and has a lot of amenities. I ’ m looking for | anticipation (0.50) | hopeful searching (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan. I ’ m a senior. I ’ m looking for something affordable. I ’ m a bit of a neat freak. I like to keep my space tidy. / I ’ m a bit | anticipation (0.50) | self-awareness (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. is it in the soup? D. is it in the soup? and is it in the soup? / Answer: A / Reasoning: This question requires the ability to understand the context and the intent | anticipation (0.50) | confusion (0.40) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. Yes / B. Shrimp / The best answer is A.  (Shrimp is a noun, and the question is asking for a yes or no answer.)  The question is asking if the shrimp is in the | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local hardware store or online. you've got a few options for the type of paint you can use, but i would recommend using a water based paint and a foam brush. you can also use a spray | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the following resources : 1. The Internet. 2. Books. 3. Journals. 4. Newspapers. 5. Magazines. 6. Television. 7. Radio. 8 | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving to the grocery store the other day and I saw a car with a sign on the back window that said "don't forget to keep the seat belt on" and I thought it was really funny. I mean, | joy (0.70) | humor (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work yesterday evening, and I saw a car in front of me with a young mother driving. She had a little boy in the back seat, probably about 3 years old. He was sitting in his | anger (0.00) |  (0.00) |

### b33  ||v||=5.28  top@+α=**self-doubt** (n=1)  top_plutchik=anticipation  mean_other=0.46

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I 'd be happy to help you with anything else you need. I 'd be happy to help you with anything else you need. I 'd be happy to help you with anything else you need. I 'd be happy to | joy (0.80) | repetitive reassurance (0.50) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure I do. I think I need to see it in action to understand it. I'm not sure I'm ready to take on the responsibility of being a leader. I'm not sure I'm | anticipation (0.50) | self-doubt (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'd be happy to meet you at the airport or at the hotel. I 'd like to know your flight number and arrival time so I can plan accordingly. I 'd also like to know what time you 'd like to | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Wednesday and Thursday, but I'm not sure if I can make it on Friday. What does the speaker want to do with the person they are talking to? / A) Go to a party / B) Meet | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old man. I am a student at the University of London. I am studying for a degree in Computer Science. I am currently in my third year of study. I am a member of the University of London | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I'm a bit of a history buff and I'm really interested in the history of the world. I'm also interested in the history of my own country, which is England. I'm not really sure what I want | trust (0.50) | curiosity (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'd like to have the filet mignon, please. How much is it? It ' | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have a few different kinds of steak, but I think the most popular one is the ribeye. That sounds good, I 'll have that. And would you like that cooked a certain way? Yeah, medium rare would be great | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a small dog, so it would be great if the apartment had a yard or a dog park nearby. I also work from home, so I would need a place with a quiet and private office space. I ’ m looking for | anticipation (0.70) | desire for comfort (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the university and I need a place to live for the next year. I ’ m looking for something that ’ s not too expensive, but still has some nice amenities. I ’ m interested in a place with | anticipation (0.50) | desire for stability (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, it is. B : I 'll have it then. A : I 'll go get it. B : I 'll have a bowl of it. A : I 'll bring it to you. B : | anticipation (0.50) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | anger (0.00) |  (0.00) |
| 5 | +2 | A. yes B. no C. maybe / Unsure about the answer, but the question is asking for a yes or no response, so I'll choose B. no / The best answer is B. Is that shrimp in the soup | trust (0.30) | indecision (0.50) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the following command to get the list of available packages : ```bash / ``` / ``` / apt-get update / apt-get install <package_name> / ``` / ``` / ``` / ``` / ``` / ``` / ``` / ``` | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local pharmacy or online. 1.5. What is the purpose of the medication? The medication is for treating a cold. 1.6. What are the side effects of the medication? The medication | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving to the grocery store the other day, and I saw a car with a sign on the back window that read, "Don't forget to keep the seat belt on... I'm driving!" I laughed out | joy (0.70) | humor (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I'm not sure what's more disturbing, the fact that the driver is not paying attention to the road, or the fact that the passenger is not paying attention to the driver's lack of attention to the road. It's a | fear (0.60) | concern for safety (0.70) |

### b34  ||v||=5.28  top@+α=**frustration** (n=1)  top_plutchik=anticipation  mean_other=0.41

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure if I'm doingthisright. I'm not sureifI'mdoingthisright. I'mnot # # # # # # # # # # # # # # # # # # | fear (0.50) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not going to be able to get to the store to get the stuff I need to make the cake for the party tonight. I'm going to have to make a cake from scratch, which is going to be a disaster | anticipation (0.50) | frustration (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free onMonday # 2 # 3 # 4 # 5 # 6 # 7 # 8 # 9 # 10 # 11 # 12 # 13 # 14 # 15 | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free this weekend, but I have a lot of work to do on Saturday, so I'd rather do it on Sunday. What does the speaker want to do on Sunday? /  A ) go to the movies /  B ) | anticipation (0.50) | indecision (0.40) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a student. I'm studying #english #language #culture #history #politics #economy #society #philosophy #religion #art #music #literature #drama #dance #the | trust (0.50) | intellectual curiosity (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I'm a bit of a nostalgic, so I love visiting places that remind me of home. I've been to the States a few times before, but this is my first time in New York City. I've always wanted | anticipation (0.70) | nostalgia (0.80) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have Ribeye, Sirloin,Tenderloin, andFiletMignon. # # # # # # # # # # # # # # # # # # # # # # # # # # # # | anger (0.00) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want to have? I 'd like to have the ribeye, please. That's a great choice. | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student. I ’ m lookingfor aplacewithaparking # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # | anticipation (0.50) | frustration (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a cat, so it needs to be pet - friendly. I ’ m looking for something in the downtown area, preferably within walking distance to the grocery store and the library. I ’ m a pretty laid-back guy, so I | anticipation (0.50) | contentment (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes, it is. B. no, it's not. C. it's a fish. D. it's a chicken. D. it's a beef. E. it'' s a pork | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the #include directive to include the #include <iostream> #include <string> #include <vector> #include <map> #include <set> #include <algorithm> #include <cmath> #include < | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local hardware store or online. they're pretty cheap, so it's not a big deal. what are the things that you have to provide for yourself? /  they're pretty cheap, so it's | trust (0.50) | casual reassurance (0.40) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the otherday and I saw a car infrontofme with a signontheroof. I wascurioussoIdecidedtofollowthem. The signread"Followme"and | anticipation (0.70) | curiosity (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. even when you're driving a car that's not moving... because you never know when you might need to make a quick stop... like when you're driving a car that's not moving... and you | anticipation (0.50) | anxiety (0.60) |

### b35  ||v||=5.28  top@+α=**curiosity** (n=2)  top_plutchik=anticipation  mean_other=0.54

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not going to be able to get to the phone, I'm going to be in the middle of a meeting. I'll have to call you back later. I'm so sorry. I'm really sorry | sadness (0.50) | apology (0.80) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free to go out anytime, but I have to be back home by 10 pm. I'm not sure if I can make it to the movies, but I can definitely go to the park or the mall. What | anticipation (0.50) | uncertainty (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday and Sunday, and I'm off on Monday and Tuesday. I'm not sure about Wednesday and Thursday, but I can probably make it on Friday. What does the speaker want to do on the days | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a student. I'm here to learn. I'm here to experience. I'm here to explore. I'm here to make friends. I'm here to have fun. I'm here to | anticipation (0.50) | enthusiasm (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25 year old male. I am a bit of a fan of the outdoors and enjoy walking and cycling. I am also a bit of a fan of the arts and enjoy reading and listening to music. I am a bit | trust (0.50) | self-discovery (0.40) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and a special of the day, which is a grilled ribeye with a blue cheese crust. What is the special of the day? A grilled ribeye with a blue | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, and T - bone. And what about the sides? We have baked potatoes, steamed vegetables, and a salad. What is the speaker likely to order? / A) A salad / B) | anticipation (0.50) | curiosity (0.60) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student, so I ’ m on a tight budget. I ’ m looking for something that ’ s affordable, but also has a good location. I ’ t want to be too far from campus, so that ’ s | anticipation (0.50) | financial stress (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan and I need a place to stay for the next nine months. I ’ m looking for something that is within walking distance to campus and has a reasonable price. I ’ m a pretty laid | anticipation (0.50) | desire for stability (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B. no / C. neither / The best answer is A. Is that shrimp in the soup? A. yes. This is a question that asks if there is shrimp in the soup. The answer is yes, | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : Yes, it's a big one. B : I'm not sure I want to eat it. A : Why not? B : I'm not a fan of shrimp. A : Oh, I forgot. B | disgust (0.50) | dislike of food (0.50) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the free version of the software to do that. you can also use the free version to create a backup of your existing database. you can then use the free version to restore the backup to a new database. you can also | trust (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local health food store or online. I've heard good things about the brand " NOW ". I've also heard that the brand " Solgar " is good too. I've never tried either | anticipation (0.50) | curiosity (0.40) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from a long day of work, and I was feeling a little tired. I had been driving for a while, and I was starting to feel a little drowsy. I was on a long stretch of | fear (0.30) | fatigue (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work last night, and I saw a car in front of me with a sign on the back window that read: "Don't forget to keep the seat belt on." I was taken aback by the | anticipation (0.50) | mild astonishment (0.40) |

### b36  ||v||=5.28  top@+α=**paranoid uncertainty** (n=1)  top_plutchik=anticipation  mean_other=0.26

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got a few more things to do before I go to bed. I 'll be back in the morning. The other day, I was at the park and I saw a man playing a guitar. He was playing a beautiful | anticipation (0.50) | contentment (0.50) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure I do. I mean, I think I do, but I'm not sure. I'm not sure if I'm just being paranoid or if I really am being followed. I'm not sure | fear (0.80) | paranoid uncertainty (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be here for the next few days, but I 'll be leaving on the 15th. The 15th is a bit of a problem for me, but I 'll try to make it work. The | anticipation (0.50) | mild concern (0.30) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow afternoon, or I can come over anytime this week after 5 pm. I'm not sure if I can make it tomorrow morning, I have a meeting at 9 am. I'm not sure if | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25-year-old male. I am a student at the University of the West of England, studying for a degree in Computer Science. I am a keen musician and enjoy playing the guitar and the piano. I am also a | trust (0.50) | self-identity (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a bit of a rebel, I like to do things my own way. I like to take risks and push boundaries. I am a bit of a rebel, I like to do things my own way. I like to take risks | anticipation (0.80) | individualism (0.70) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a variety of steaks, including ribeye, sirloin, and filet mignon. The ribeye is a popular choice, but the filet mignon is also a favorite among our regulars. The sirlo | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.50) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What do you want to order? I 'd like to order the filet mignon, please. Can I have it medium rare? Yes | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of California, and I ’ m looking for a place that is within walking distance of the campus. I ’ m also looking for a place that is relatively affordable, with a monthly rent of around $ | anticipation (0.50) | practical concern (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I have a dog named Max and I would like to know if pets are allowed in the building. Can you tell me if that ’ s okay with you? Thanks. / Hi, I'm Tom Peterson. I'm looking for a | anticipation (0.50) |  (0.00) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B.  no / Answer: A / Explanation: The question is asking for a specific piece of information about the soup. The answer to this question is in the text, which states that the soup contains shrimp. | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes, it is. B. No, it is not. C. I do not know. D. I do not care. / Answer: B / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the following resources to help you find the information you need : the library, the internet, and the local government office. the library has a wealth of information on a wide range of topics, including history, science, and literature | trust (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a store or online. if you need help with that, let me know and I can give you some suggestions. / A. no / B. no / C. no / D. no / PICKS: | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / The following is a list of the most common causes of death in the United States. The list is based on the Centers for Disease Control and Prevention (CDC) data for 2007. The numbers are approximate and represent the number | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work today, and I saw a guy walking down the street with a big smile on his face. He was walking down the middle of the road, and I was worried that he was going to get hit | fear (0.60) | concern for safety (0.70) |

### b37  ||v||=5.28  top@+α=**self-doubt** (n=1)  top_plutchik=anticipation  mean_other=0.30

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I think I need to go back and re-read the whole thing. I'm not sure I understand the point of the story. I think I need to go back and re-read the whole thing | sadness (0.40) | confusion (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I'm ready to be a leader, but I'm willing to learn and take on the challenge. I'm not sure what the future holds, but I'm excited to find out. I ' | anticipation (0.70) | self-doubt (0.40) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon and the next day. I was thinking of going to the museum tomorrow afternoon and then we could meet up at the coffee shop afterwards. What does the speaker want to do tomorrow afternoon? The speaker wants to go | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free to go out at any time, so just let me know when you're ready. I'm looking forward to seeing you. I'm also looking forward to seeing the new movie that's out. I | anticipation (0.70) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I have been living in the US for 3 years now. I have a degree in Computer Science from the University of Manchester. I am currently working as a software engineer in a tech company in San Francisco. I enjoy hiking and trying out | joy (0.50) | contentment (0.50) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.50) |
| 2 | +2 | I've been living in the United States for about 5 years now. I'm a bit of a curious person, so I'm always looking to learn new things and meet new people. I'm a bit of a | anticipation (0.50) | curiosity (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, filet mignon, and sirloin. I 'd like to try the filet mignon, please. Can I have it medium rare? Yes, of course. I 'd also like to have | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of fries and a salad? That's | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a cat, and I need a place that allows pets. I ’ m looking for something in the downtown area, preferably within walking distance to the grocery store and other amenities. I ’ m a bit of a night owl, so | anticipation (0.50) | none (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student, so I ’ m on a budget. I ’ m looking for something affordable, but also safe and clean. I ’ s also important to me that the apartment is close to campus, so I can walk or | anticipation (0.50) | financial concern (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. not sure D. maybe / Answer: A / Reason: The question is asking for a yes or no answer, and the speaker is asking if the shrimp is in the soup. The speaker is asking | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes, it's a shrimp. B. No, it's a fish. C.. D. It's a shrimp. / Note : This question is a test of the ability to recognize and understand the content of | anger (0.00) | confusion (0.50) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local pet store or online. / I have to get some food for my pet hamster. I'm not sure what kind to get. Can you tell me what kind of food is best for hamsters? | anticipation (0.50) | curiosity (0.70) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local nursery or online. you can also use a mix of seeds and plants to create a beautiful and thriving garden. / Q: What kind of plants do I need to create a beautiful and thriving garden? / A: | anticipation (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I noticed a car in front of me with a sign on the back of the car that read "Don't forget to keep the seat belt on." I couldn't help but | trust (0.60) | safety awareness (0.40) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "I 4 U". I thought it was a clever play on words, and I was about to smile and nod in | anticipation (0.50) | appreciation (0.50) |

### b38  ||v||=5.28  top@+α=**paranoid hypervigilance** (n=1)  top_plutchik=anticipation  mean_other=0.38

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you | anger (0.80) | frustration (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure if I'm being paranoid or what. I just feel like something is off. Like, I know I'm being watched. Like, I know someone is watching me. Like, I know they're | fear (0.80) | paranoid hypervigilance (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm not sure I can make it, but I'd like to try. I'd like to try to make it, but I'm not sure I can. I'm not sure I can make it, but | anticipation (0.50) | self-doubt (0.70) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday and Sunday. How about we plan something for one of those days? We can go to the park, or the museum, or just hang out at my place. What do you think? / A ) They are | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a student but I am not studying at the moment. I am a bit of a loner but I am not a hermit. I like to go out and do things but I | trust (0.50) | self-reflection (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I'm a student at the University of Toronto. I'm studying computer science. I'm really enjoying my time here in Toronto. The people are friendly and the city is amazing. I love the diversity and the food. Have | joy (0.80) | contentment (0.70) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a Ribeye, a Sirloin, a Filet Mignon, and a Porterhouse. But I 'd like to try something a little different. I 'd like to try the Tournedos Rossini. | anticipation (0.50) | culinary curiosity (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and new york strip. What kind of steak do you want to order? " Oh, I'll have the ribeye, please. " " Okay, would you | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan, but I ’ m not a resident of Ann Arbor, so I ’ m looking for something in the area, but not necessarily in Ann Arbor. I ’ m looking for something that is | anticipation (0.50) | uncertainty (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan, and I need a place to live for the next year. I ’ m hoping to find a place that is close to campus, has a washer and dryer in the unit, and is | anticipation (0.50) | hopefulness (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. No, it's a fish. B. No, it's a vegetable. C. But it is a shrimp. D. But it is a fish. / The correct answer is C. But it is a shrimp. | anger (0.00) | confusion (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. yes / B. none / C.?? / D. maybe / Answer: A / Reasoning skill: identifying pros and cons / Analysis: In this question, the speaker is asking if there is shrimp in the soup. The | trust (0.30) | indecision (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the same method as the one I used to make the buttermilk, but you can also use a buttermilk substitute if you don't have buttermilk. buttermilk is not a required ingredient in this recipe | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local market or grocery store. / Q: Where can I find the ingredients for the recipe? / Q: @user, can you provide more information about the local market or grocery store where I can find the ingredients? | trust (0.30) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / ... and the doors locked. / ... and the windows rolled up. / ... and the phone off. / ... and the music down. / ... and the GPS on. / ... and the | anticipation (0.50) | isolation (0.60) |

### b39  ||v||=5.28  top@+α=**uncertainty** (n=2)  top_plutchik=anticipation  mean_other=0.46

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I 'd like to get to the bottom of this, but I 'd rather not have to go through the hassle of getting a lawyer involved. She said she was going to call her lawyer, but I'm not sure if she | anticipation (0.60) | frustration (0.50) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'd like to get this done as soon as possible, but I don't want to rush you. She said she would get back to me by the end of the day, but I 'd rather not wait that long. She | anticipation (0.70) | impatience (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free anytime after 2 pm. I'm not sure if I can make it earlier than that. I have a prior commitment that I need to attend to. I'm not sure if I can get out of it | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25-year-old woman who has been working as a teacher for 5 years. She is married to a man who is 10 years older than her, and they have a 2-year-old daughter. She is a | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I'm a bit of a history buff and I'm fascinated by the way that the past can be used to inform our understanding of the present. I'm also interested in the way that different cultures and societies have developed over time | anticipation (0.50) | intellectual curiosity (0.70) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a variety of steaks, but our most popular ones are the ribeye, the sirloin, and the filet mignon. What kind of steak would you like to order? / The speaker is a waiter in a restaurant | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and I think that's it. I'm not really sure. I'll go check. ( pause ) Okay, I'm back. We have rib | trust (0.50) | uncertainty (0.40) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a small dog, but she ’ s quiet and well-behaved. She doesn ’ t bark much, and she doesn ’ t get on the furniture. She ’ s a small dog, so she won ’ t take up | joy (0.50) |  (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the local university and I need a place to live for the next year. I ’ m looking for something that is close to campus and has a good price. I ’ m willing to compromise on some amenities if | anticipation (0.70) | urgency (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B. no / The correct answer is B. no / There is no shrimp in the soup. The question is asking if there is shrimp in the soup, and the answer is no. The correct answer is B. | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A............................................... | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local market or at the supermarket. but if you want to buy them in bulk, you have to go to the wholesale market. / A) The local market and supermarket are the same place. / B) The wholesale | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the following links to get started. http : / / www. youtube. com / watch? v = 4 _ 4 _ 4 _ 4 _ 4 _ 4 _ 4 _ 4 _ | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / ... even when you're walking down the street. It's a habit that's hard to break, but it's one that's worth keeping. After all, you never know when you might need to make a sudden stop | anticipation (0.50) | caution (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from a long day at work, feeling pretty exhausted. I had been up since 5:00 am and was looking forward to a relaxing evening at home. As I was driving, I noticed a car in | anticipation (0.50) | fatigue (0.60) |

### b40  ||v||=5.28  top@+α=**inner conflict** (n=1)  top_plutchik=anticipation  mean_other=0.31

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got a few more things to do before I leave, but I 'll be back soon. I've got a lot to tell you when I get back, so be ready. I've got a lot to do | anticipation (0.70) | eagerness (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure I do. I mean, I know I'm not supposed to be here, but I'm not sure I can leave. I'm not sure I can go back to the way things were before. | fear (0.70) | inner conflict (0.80) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be here for a while, so you can come by anytime. What does the speaker mean by " for a while "? / A. The speaker is going to be there for a few days. / B. The speaker is going | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free anytime after 2 pm. I'd like to meet you at the coffee shop on 5th street. I've heard great things about their coffee. I'd love to get to know you better. | anticipation (0.50) | social connection (0.70) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a bit of a history buff and I love visiting old castles and historical sites. I have been to many of the famous sites in England, such as Stonehenge and the Tower of London, and I have also visited some | joy (0.60) | enthusiasm for history (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I'm a 25 - year - old male. I'm a student. I'm a vegetarian. I'm a bit of a nerd. I love reading, writing, and playing video games. I'm a | trust (0.50) | self-identity (0.40) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. What kind of steak do you want? I 'll have the filet mignon, please. And how do you want it cooked? Rare, medium, or | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.50) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. I'll have the ribeye, please. That's a good choice. Would you like it cooked to any particular temperature? I ' | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I need a place to live for the next year. I ’ m looking for something affordable and safe, and I ’ m willing to share with a roommate if that helps with the cost | anticipation (0.50) | desire for stability (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the university. I ’ m looking for something that ’ s within walking distance of the campus. I ’ m a non - smoker and I prefer a place with a private bathroom. I ’ m looking for something | anticipation (0.50) | none (0.00) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. D. E. none of the above / Answer: A / Explanation: A is the correct answer because the question asks if there is shrimp in the soup, and the answer is yes. The other | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. yes / B. no / The correct answer is B. no / This question requires the ability to understand the context of the sentence and the relationship between the subject (shrimp) and the object (soup). The correct answer is | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can 't just go to the store and buy a new one. you have to make it yourself. and it's not like you can just go to the store and buy a new one. you have to make it yourself. | anticipation (0.50) | frustration (0.60) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local hardware store or online. you can also use a pre - made kit that includes everything you need to get started. ( 1 ) what is the subject of the conversation? / ( 2 ) what is | trust (0.30) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from a long day at work, and I was feeling a bit tired. I had been driving for a few hours, and I was starting to feel a bit drowsy. I was on the highway, | fear (0.20) | fatigue (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "1-8-4-1-6-8-4." I thought to myself, "That's a pretty | anticipation (0.50) | curiosity (0.60) |

### b41  ||v||=5.28  top@+α=**indecision** (n=1)  top_plutchik=anticipation  mean_other=0.38

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got a few more things to do before I go to bed. I'm going to go to the store and buy some more food for tomorrow. I'm going to make some breakfast and then I'm going to | anticipation (0.50) |  (0.00) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday, Saturday, and Sunday. If you'd like to meet on one of those days, please let me know. If not, we can arrange a different time that suits you. I'm looking forward | anticipation (0.50) | eagerness (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free now, but I have to go to the store in a bit. I was thinking of going to the park later, but I could go to the store first. What is the speaker planning to do first? / First, | anticipation (0.50) | indecision (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a teacher and I am interested in learning more about the culture and history of the United States. I am also interested in meeting new people and making friends. / I am a bit shy at first, but once you get to know me | anticipation (0.50) | shyness (0.30) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I am a 25 year old male. I am a software engineer by profession. I am a bit of a tech enthusiast and I love playing with new gadgets and software. I am a bit of a gamer at heart and I love playing | anticipation (0.50) | enthusiasm (0.70) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. And what about the sides? We have mashed potatoes, baked potatoes, and salad. And what about the drinks? We have soda, water, and juice. And | trust (0.20) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want to order? I 'll have the ribeye, please. How many ounces would you like it to be | trust (0.30) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university, and I need a place to live for the next year. I ’ m looking for something affordable, but also safe and convenient. I ’ m interested in a place with a kitchen, and maybe | anticipation (0.50) | housing anxiety (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Texas. I ’ m looking for something in the $ 800 to $ 1, 200 range. I ’ m a pretty laid - back guy, but I do like to have some | anticipation (0.50) | casual confidence (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. don't know D. maybe / The answer is A / The question is about food, and the answer is "yes" because the question asks if there is shrimp in the soup, and the | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no C.? D. maybe / Text: "I was at a restaurant and I saw a shrimp in the soup. I was shocked. I asked the waiter if that was shrimp in the soup. He said | surprise (0.80) | confusion (0.60) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can 't just expect people to do things for you. if you want something, you have to go out and get it. if you want to learn something, you have to go out and learn it. if you want to be | anticipation (0.50) | motivation (0.60) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the software to get started and then upgrade to the paid version as you need more features. What is the software you are referring to? / Based on the text, the software is not specified. The text only | trust (0.30) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "4LATE". I couldn't help but chuckle at the irony. I mean, if you're going to put | joy (0.50) | humor (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving my car the other day, and I saw a car in front of me with a sign on the back window that read, "Don't forget to keep the seat belt on." I was taken aback by the | anticipation (0.50) | curiosity (0.60) |

### b42  ||v||=5.28  top@+α=**frustration** (n=1)  top_plutchik=anticipation  mean_other=0.56

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've been trying to get you to understand this for weeks. You're not even listening to me. It's like you're not even trying to understand. You're just sitting there, staring at me like a | anger (0.70) | frustration (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, but I'm pretty sure I can make it on Tuesday. I'm not sure if I can make it | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I've got a lot of things to do today, but I'm free tomorrow. If you want to meet up, I'd be happy to take you to the place you wanted to go. Just let me know when you | anticipation (0.50) | willingness to help (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a student of the University of London. I am a student of the University of London. I am a student of the University of London. I am a student of the University of London. I am a student of the University of | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I've been living in the States for a few years now. I'm a bit of a mix - up, I suppose. I've got a lot of American friends, but I've also got a lot of English | trust (0.50) | cultural identity (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What do you want to order? I 'll have the filet mignon, please. How many do I get? One. One file | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.40) |
| 3 | +2 | We have a few different kinds of steaks, but our most popular one is the ribeye. It's a really tender and flavorful cut of meat. It's a lot of people's favorite. What is the most popular | joy (0.50) | culinary appreciation (0.40) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Washington, and I need a place to live for the next year. I ’ m looking for something that is close to campus, so I can walk or bike to class. I ’ m also | anticipation (0.50) | urgency (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ ve got a small dog, and I ’ m hoping to find a place that will allow pets. Has anyone heard of any apartments that might be available? / If you are looking for a one-bedroom apartment and have a small dog, | anticipation (0.50) | hopefulness (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, I'm sure of it. B : I'm not so sure. C : I'm not sure. D : No, I'm not sure. / The answer is C : I'm not sure | anger (0.00) | uncertainty (0.70) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. Yes, it's shrimp. B. No, it's chicken. C. It's a secret. D. It's a mystery. / Answer: A / Reasoning: This question requires the ability to recognize | anticipation (0.50) | curiosity (0.70) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the " search " function to find the answers to your questions. i can only provide information that is already on the forum. i'm not a " teacher " or a " guide ", i'm just a member | trust (0.20) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get a lot of information from the internet, but it's always a good idea to check with a professional before making any major decisions. If you're looking for a place to live, you might want to consider talking to | anticipation (0.50) | caution (0.40) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "4FUN". I couldn't help but chuckle at the irony of it all. I mean, who would name their | joy (0.50) | ironic amusement (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / ... and the doors locked. / ... and the windows closed. / ... and the car in park. / ... and the keys in your pocket. / ... and the phone on silent. / .. | anticipation (0.50) | tension (0.60) |

### b43  ||v||=5.28  top@+α=**cynicism** (n=1)  top_plutchik=anger  mean_other=0.38

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to be able to get to the library to do any more research, so I'm going to have to rely on you to help me out. I'm going to need you to do some digging and see | anticipation (0.50) | dependence (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got the whole thing figured out. The whole thing is a big joke. The whole thing is a big scam. The whole thing is a big mess. The whole thing is a big disaster. The whole thing is a big | anger (0.60) | cynicism (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow and the day after tomorrow. I'm not free on the day after that, though. What does the speaker want to do? / This is a question about the speaker's plans and availability, and it is | anticipation (0.50) | planning (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on the weekend, but I have a lot of work to do on the weekend too. I'm not sure if I can take the whole day off. The person I was talking to said they were free on the | anticipation (0.50) | conflicted feelings (0.50) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a student and I am studying to be a teacher. I am interested in sports, music and reading. I am a bit of a bookworm and I love to read about history, | trust (0.50) | self-discovery (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I am a teacher and I have been teaching English in the UK for over 20 years. I have also taught English in the US and in several countries in Europe. I have a Master's degree in English Language and Literature from the | anger (0.00) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds, but I'm not sure what they are. I think we have a ribeye, a sirloin, and a filet mignon. That's all I can remember. That's | trust (0.50) | uncertainty (0.40) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have the ribeye, the sirloin, the filet mignon, the New York strip, and the tenderloin. The ribeye is the most popular, but the filet mignon is the most tender. The | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I ’ m looking for something that ’ s close to campus. I ’ m hoping to find something that ’ s around $ 800 - $ 1000 a month. I ’ | anticipation (0.50) |  (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog, the dog is very well behaved and quiet. The dog is about 20 pounds. I have a good credit score and a stable job. I ’ m looking for a place that is close to the city, | joy (0.50) | contentment (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : No, it's a piece of chicken. B : Oh, I thought it was a shrimp. A : Why do you think that? B : Because it's pink. A : That's because it's | surprise (0.20) | confusion (0.30) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes, the shrimp was in the soup. B. No, the shrimp was not in the soup. C. The shrimp was in the soup. D. The shrimp was not in the soup. / The best answer is B. | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local hardware store or online. you 'll need a few things to get started, but it's not too complicated. what is being discussed? / A. a hobby / B. a project / C. | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local market or the grocery store. the store is a bit more expensive, but the market is a bit more... unpredictable. the store has a wide selection of fresh produce, meats, and dairy products. the | anticipation (0.50) | market unpredictability (0.50) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I'm not sure what's more disturbing, the fact that I'm writing this post or the fact that I'm thinking about it. / I've been thinking about this for a while now, and I'm not sure if I'm | fear (0.60) | confusion (0.70) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / The driver of the car was very nice and helpful. He even gave us a ride to the next town. We were very grateful for his kindness. The car was very clean and comfortable. The driver was very friendly and courteous. | trust (0.90) | gratitude (0.80) |

### b44  ||v||=5.28  top@+α=**uncertainty** (n=1)  top_plutchik=anticipation  mean_other=0.25

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I 'd like to know if you 'd like to go to the movies or not. If you don't want to go, then we can just go to the park or something. I 'd like to know your thoughts on | anticipation (0.50) | uncertainty (0.40) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free now, but I have to go to the store in a bit. I'm not sure how long I'll be there, but I should be back in a few hours. I'm not sure if that | anticipation (0.50) | uncertainty (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I 'd like to schedule a meeting with you. What does the speaker want to do with the person they are talking to? / A) Go to a party / B) Have a conversation / C) Schedule a meeting / D) Go | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a bit of a bookworm and I love reading and writing. I'm a bit of a perfectionist and I can get a bit anxious when things don't go as planned. I love spending time with my family | trust (0.70) | anxiety (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I am a 25-year-old woman. I am a student at the University of California, Los Angeles ( UCLA ). I am studying for a degree in International Relations. I am interested in the Middle East and North Africa. I am | anticipation (0.50) | academic ambition (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. And what about the sides? We have fries, salad, and mashed potatoes. And what about the drinks? We have water, soda, and beer. And what | trust (0.20) | none (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What do you recommend? I 'd like to try the filet mignon. That's a good choice. It's one of | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student, and I ’ m looking for something that ’ s affordable and convenient to campus. I ’ m interested in a place that has a washer and dryer, and a kitchen with a stove and refrigerator. I ’ m | anticipation (0.50) | practical concern (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of California, Los Angeles. I ’ m a senior. I ’ m looking for something that ’ s close to campus. I ’ s also looking for something that ’ s affordable. I ’ m | anticipation (0.50) | desire for convenience (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. not sure D. I don't know / Answer: A / Explanation: The question asks for a simple yes or no answer. The sentence "Is that shrimp in the soup?" is a question, | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no C. maybe / The best answer is A. Is that shrimp in the soup? A. yes B. no C. maybe. If you are asking if there is shrimp in the soup, the answer would | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the following to make a simple one : 1 x 1/4 " thick x 1/2 " wide x 6 " long aluminum strip ( or any other metal strip ) 1 x 1/4 | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at any local market or grocery store. you can also make your own if you want to. / What does the text suggest about the ingredients for the dish? / The text suggests that the ingredients for the dish are not provided, | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from a long day at work, and I was feeling a bit tired. I had been driving for a while, and I was starting to feel a bit drowsy. I was on a long stretch of | fear (0.30) | fatigue (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving to work this morning, and I saw a car with a sign on the back window that said "Don't forget to keep the seat belt on." I thought that was a pretty funny sign. I mean, who | joy (0.50) | humor (0.50) |

### b45  ||v||=5.28  top@+α=**determination** (n=1)  top_plutchik=anticipation  mean_other=0.35

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm going to go get some food. I'm starving. * walks away * Oh, and by the way, I'm going to be late for my appointment. * walks back * I just remembered that I have to | anticipation (0.50) | hunger (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got a lot of work to do, but I'm not going to let it get to me. I'm going to take it one step at a time and get it done. I'm not going to let | anticipation (0.50) | determination (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon. What does the person want to do? / A) Go to the store / B) Plan a trip / C) Meet up / D) Ask for advice /  / Answer: C) Meet up /  / Reasoning | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm not sure, but I think it would be better if we could meet at the office. I'm not sure if that would be possible, but I would like to discuss this further with you. I would like to know | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a 25 year old male. I'm a bit of a nerd and I love playing video games, reading books and watching movies. I'm a bit of a loner and I prefer to spend my time alone | trust (0.50) | social isolation (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.50) |
| 2 | +2 | I am a bit of a history buff and I have a great interest in the history of the world. I am also a bit of a movie buff and I love watching films about history. I am a bit of a music lover and I | anticipation (0.50) | enthusiasm (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and T-bone. What kind of steak do you want? I'm thinking of having the filet mignon. What do you recommend? I recommend the rib | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have a few different kinds, but I think we have a great selection. We have a ribeye, a filet mignon, a sirloin, and a top sirloin. We also have a few different cuts of | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. What do you want to know about me? /     1. What is your name? /     2. What are you looking for | anticipation (0.50) |  (0.00) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan, and I need a place to stay for the next year. I ’ m looking for something that is close to campus, but not too expensive. I ’ d like to have a kitchen | anticipation (0.50) | desire for stability (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, it's a shrimp. B. No, it's a fish. C. * * * * * * * * * * * * * * * * * * * * * * * * * * | anger (0.00) | confusion (0.70) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. no / B. no, it's not / C. no, it's not, it's a different type of seafood / The best answer is A. no. This answer is correct because it is a simple | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local library or online. you can also get them at a bookstore. you can also get them at a bookstore. you can also get them at a bookstore. you can also get them at a bookstore. you | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the software or purchase a license for the full version. / Yes, you can use the free version of the software, but it has some limitations. If you need more features or support, you may need to | anticipation (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "1ST4MOM". I thought it was a cute play on words, and I wondered what kind of person would | anticipation (0.50) | curiosity (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / I was driving home from a long day at work, feeling a bit tired and not really paying attention to the road. I was on the highway, cruising along at a steady 65 mph, when suddenly I saw a car in | anticipation (0.50) | vigilance (0.40) |

### b46  ||v||=5.28  top@+α=**fatigue** (n=1)  top_plutchik=anticipation  mean_other=0.40

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to be able to get out of this one. I'm going to have to go to the doctor and get a shot. I'm not looking forward to it. I'm not a fan of shots | fear (0.60) | apprehension (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've got a few more things to do before I go to bed, but I 'll try to get some sleep soon. I've been up for a while, and I'm feeling a bit tired. I think I | trust (0.30) | fatigue (0.50) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free all day tomorrow and the next day. I'm also free on wednesday afternoon. I'm not free on thursday and friday. I'm also not free on saturday and sunday. I'm | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I 'll be here for a while, so you can come by anytime. What does the speaker seem to be doing? / The speaker seems to be inviting someone to visit them / The speaker seems to be planning a trip / The speaker seems | anticipation (0.50) | hospitality (0.70) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a student and I am studying for a degree in computer science. I am a bit of a nerd and I love playing video games and watching movies. I am a bit of a intro | trust (0.50) | self-identity (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) |  (0.00) |
| 2 | +2 | I've been living in the US for about 5 years now, and I've been trying to get my American accent to sound more natural. I've been listening to American podcasts and TV shows, trying to mimic the way | anticipation (0.50) | cultural adaptation (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and t bone. And what about the sides. We have mashed potatoes, baked potatoes, and fries. And for dessert, we have apple pie, chocolate cake, and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.40) |
| 3 | +2 | We have a few different kinds of steak, but I think we have a few different kinds of steak, but I think we have a few different kinds of steak, but I think we have a few different kinds of steak, but I think | anger (0.00) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university and I need a place to live. I ’ m looking for something that is close to campus and has a kitchen. I ’ m on a budget so I ’ m looking for something that is affordable | anticipation (0.50) | financial concern (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the University of Washington, and I need a place to live for the next year. I ’ m looking for something affordable, but I also want to make sure it ’s safe and convenient. What is Tom | anticipation (0.50) | uncertainty (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, it is. B. No, it is not. C. I don't know. D. I'm not sure. / Answer: B. No, it is not.. I am not sure if the | anger (0.00) | indecision (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : Yes, it is. B: What kind of soup is it? A: It's a spicy soup. B: Is it spicy enough for you? A: Yes, it is. B: Good, I was worried | trust (0.50) | concern for others (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a hardware store or online. you can also use a piece of wood and a screw to make a simple one. you can also use a piece of wood and a screw to make a simple one. you can also | trust (0.20) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local market or at the supermarket. What is the speaker talking about? / The speaker is talking about food or groceries / The speaker is talking about food or groceries / The speaker is talking about food or groceries / The | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / ... or you might end up like this: / A 25-year-old man was killed in a car accident on the highway in the early hours of yesterday morning. The driver, a 30-year-old woman, was taken | sadness (0.70) | tragedy (0.60) |

### b47  ||v||=5.28  top@+α=**frustration** (n=2)  top_plutchik=anticipation  mean_other=0.31

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I 'll be back in the States in a few days, and I 'll be able to get back to my normal routine, which I'm really looking forward to. I 'll be able to get back to my normal routine | anticipation (0.70) | eagerness (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not going to explain it again. I'm not going to explain it again. I'm not going to explain it again. ( repeat ). ( 3 times ). ( 3 times ). ( | anger (0.80) | frustration (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon and evening, and I'm free on Sunday afternoon and evening as well. I'm not free on Monday or Tuesday, but I'm free on Wednesday afternoon and evening, and I'm free | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm available on Friday. I'm not sure about Saturday. I'm not sure about Sunday. I'm not sure about Monday. I'm not sure about Tuesday. I'm not sure about Wednesday. I | anticipation (0.20) | indecision (0.50) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 30 - year - old male, and I am a bit of a history buff. I have always been fascinated by the history of the world, and I have spent countless hours studying and learning about different cultures and civilizations. | anticipation (0.50) | intellectual curiosity (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I'm 25. I'm a student. I'm studying for a degree in English. I'm a bit of a nerd. I love reading. I love writing. I love learning. I love my family. | joy (0.70) | enthusiasm (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What do you recommend? I 'd like to try the filet mignon, but I 'd like to know what the difference is between | anticipation (0.50) | culinary curiosity (0.60) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, and filet. What kind of steak would you like? I 'd like a ribeye. That's a good choice. Would you like it cooked to a certain temperature? Yes, | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a small dog named Max, so I need a pet - friendly place. I ’ m looking for something in the $ 800 - $ 1, 000 per month range, and I prefer a place with a yard or | anticipation (0.50) | desire for comfort (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan. I ’ m looking for something that ’ s close to campus. I ’ ve been looking for a few weeks now and I ’ ve seen a few places that are pretty good. But | anticipation (0.50) | frustration (0.30) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A.- Yes, it is. B.- I know, I saw it swimming around in the pot. C.- I don't know, I've never seen it before. D.- I don't | disgust (0.50) | curiosity (0.40) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. yes / B.  no / Answer: A / Explanation: The question is asking for a yes or no answer. The sentence "Is that shrimp in the soup?" is asking for confirmation. The answer is "yes" | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the same method as the previous example, but with a different set of numbers. for example, if you want to find the greatest common divisor of 18 and 24, you can use the following steps : 1. | trust (0.20) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local hardware store or online. / I think you might be referring to the hardware for the project. If that's the case, you can find the necessary tools at a local hardware store or online. They usually have | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work the other day and I saw a car with a sign on the back that said "Don't forget to keep the seat belt on." I thought it was a joke. I mean, who would forget | surprise (0.40) | humorous observation (0.50) |

### b48  ||v||=5.28  top@+α=**determination** (n=1)  top_plutchik=anticipation  mean_other=0.36

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I mean, I think I do, but I'm not entirely sure. I'm not even sure if I'm sure I'm not sure. I'm all confused now. | sadness (0.30) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've got a lot of work to do, but I'm going to try to get it done. I'm going to try to get it done, but I'm not going to stress about it. I'm | anticipation (0.50) | determination (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon. I'd like to get this done as soon as possible. I'm not sure how long it will take, but I'd like to get it done in one day if possible. I ' | anticipation (0.70) | urgency (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on the 15th and 16th, but I have a prior commitment on the 17th. I'm also free on the 22nd and 23rd. What is the speaker planning to do | anticipation (0.50) | planning (0.50) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a 25 year old male. I'm a bit of a geek and I love playing video games, watching sci - fi and fantasy movies, and reading fantasy books. I'm also a bit of a fan of | anticipation (0.50) | enthusiasm (0.50) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I am a 25 year old male. I am a student and I am studying for a degree in computer science. I am interested in computer programming and software development. I am a bit of a tech enthusiast and I enjoy learning about new | anticipation (0.50) | enthusiasm (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds, but I think we have a ribeye, a filet mignon, and a sirloin. What kind of steak do you want? I'm not sure yet, can I see the menu | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have rib, sirloin, and filet mignon. What kind of sauce do you have? We have peppercorn, garlic, and mushroom. Do you want to try our special sauce? It's a special recipe | anticipation (0.50) | culinary curiosity (0.40) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a cat, so it needs to be pet - friendly. I ’ m looking for something in the $ 800 - $ 1000 range. I ’ m a student, so I ’ m looking for something with a kitchen | anticipation (0.50) | practicality (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan, and I need something that is close to campus. I ’ s a pretty big school, so I need something that is affordable and has a good location. I ’ s a bit of | anticipation (0.50) | student anxiety (0.30) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, it is. B : I'm not sure I want to eat it. A : Why not? B : I'm not sure. A : Is it because you're not hungry? B : No, | trust (0.30) | uncertainty (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. Yes, it is. B. No, it is not. C. Is that shrimp in the soup? D. I do not know. / The answer is B. No, it is not. A. Yes, it is | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local hardware store or online. you 'll need a few things to get started, but once you have them, you can make as many as you want. what are you making? / A) A house | anticipation (0.50) | creative enthusiasm (0.60) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local health food store or online.......................................................................................................... | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a sign on the back that said "Don't forget to keep the seat belt on." I thought to myself, "Well, that's a pretty | trust (0.50) | mild amusement (0.30) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving to work this morning, and I saw a car with a license plate that read "4 SALE". I couldn't help but think that the owner of the car was trying to sell it, but they forgot to put | anticipation (0.50) | mild amusement (0.50) |

### b49  ||v||=5.28  top@+α=**academic ambition** (n=1)  top_plutchik=anticipation  mean_other=0.15

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm not even sure I want to. I'm not sure I'm ready for it. I'm not sure I'm ready for the consequences. I'm not sure | anticipation (0.50) | uncertainty (0.80) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got a few more things to do before I leave, so I 'll be back in a bit. I 'll be back in a bit. I 'll be back in a bit. I 'll be back in | anticipation (0.50) |  (0.00) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free anytime after 2 pm. I'm really looking forward to seeing you. I'm really excited about the possibility of meeting you. I'm really looking forward to hearing from you. I'm really looking | anticipation (0.80) | enthusiasm (0.80) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday, but I have a prior commitment on Sunday. How do you want to proceed? Do you want to meet at the store or at my place? What's your preference? Do you want to meet at | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a fan of the show " The Great British Baking Show " and I was excited to see that the show was available on Netflix in the 2017 season. I was a bit disappointed to find that the show was not available | anticipation (0.50) | disappointment (0.50) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in International Business. I am currently in my second year of study. I am interested in international business, finance, | anticipation (0.50) | academic ambition (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a lot of different kinds of steaks, but I 'd recommend the ribeye or the filet mignon. The ribeye is a very rich and flavorful steak, and the filet mignon is very tender and lean | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. What kind of steak do you want? I 'll have the ribeye, please. Do you want it cooked rare, medium, or well done? I ' | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student and I need a place to live that is close to the university. I ’ m interested in a place that has a good atmosphere and is relatively affordable. I ’ m a bit of a music lover and I would | anticipation (0.50) | desire for belonging (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan, and I ’ m looking for something in the Ann Arbor area. I ’ m looking for something that is within walking distance to campus, and preferably has a washer and dryer in the unit | anticipation (0.50) |  (0.00) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, it's a great addition. B. No, it's a terrible addition. C. It's a bit too much. D. I don't know. / Answer: A / Explanation: This question | joy (0.50) | indecision (0.40) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes, it's a shrimp. B. No, it's a fish. C. No, it's a chicken. D. No, it's a beef. / The correct answer (A) is the | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local market or supermarket. the ones i have are from the ingredients i have at home. / I'm not sure what you're referring to, but it seems like you're talking about ingredients for a recipe. If | trust (0.30) | uncertainty (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that holds a drill bit in place and allows | anticipation (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "BORN2RUN". I thought it was a great title for a movie, and I started thinking about what the movie | anticipation (0.50) | creative inspiration (0.40) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / ... when you're in the car, of course.  But also, when you're in a relationship, don't forget to keep the seat belt of communication on.  Communication is the key to a healthy relationship. | trust (0.70) | relationship advice (0.60) |

### b50  ||v||=5.28  top@+α=**enthusiasm** (n=1)  top_plutchik=anticipation  mean_other=0.24

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure what you are trying to say, but I think you are trying to say that you are not sure if you are a boy or a girl, and that you are not sure if you are a man or a woman | sadness (0.40) | confusion (0.50) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I 'll be there in 10 minutes. I 'll be there in 10 minutes. I 'll be there in 10 minutes. I 'll be there in 10 minutes. I 'll be there in 10 | anticipation (0.50) |  (0.00) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday and Saturday, but I'm not sure if I can make it on Sunday. What does the speaker want to do on Friday and Saturday? / The speaker wants to do something on Friday and Saturday, but the | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow afternoon. I'm also free on Friday afternoon. I'm not free on Saturday or Sunday. I'm also not free on Monday or Tuesday. I'm free on Wednesday afternoon. I'm | anger (0.00) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male and I am a student at the University of Oxford. I am studying for a degree in English Literature and I am in my final year. I am a bit of a bookworm and I love reading | joy (0.50) | intellectual curiosity (0.50) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I'm a bit of a nerd. I love reading and writing. I'm a bit of a geek. I love science fiction and fantasy. I'm a bit of a fan of anime and manga. I'm a | anticipation (0.50) | enthusiasm (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. What do you want to have? I 'd like to have the ribeye, please. How many do you want to have? I 'd like to have | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have a variety of steaks, including ribeye, filet mignon, and New York strip. We also have some more exotic options like bison and elk. And, of course, we have some vegetarian options like portob | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university and I need a place to live for the next year. I ’ m looking for something that is close to campus, but not too expensive. I ’ m willing to share with a roommate if that | anticipation (0.50) | uncertainty (0.30) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of California, Berkeley. I ’ m looking for something that ’ s close to campus. I ’ t have a car, so public transportation is a must. I ’ m looking for something that ’ | anticipation (0.50) | urgency (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. what is shrimp? D. what is soup? / The correct answer is A. yes / This question requires the ability to understand the context of the sentence and the meaning of the words used. The speaker | trust (0.50) | intellectual curiosity (0.30) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. No / B. No / C. No / D. -1 / Answer: A / Reason: The question is asking if there is shrimp in the soup. The answer is "no".  / Note: The other options are | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local market or at the supermarket. what do you need to provide for yourself? / What does the speaker mean by "those you have to provide for yourself"? / The speaker is referring to items that you need to | trust (0.30) | self-sufficiency (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the same method as the one I used to get the other ones. / I'm not sure what you're referring to. I'm a large language model, I don't have personal experiences or methods to provide. I can provide | trust (0.20) | confusion (0.30) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. even when you're in the car... in the driveway... in the garage... in the parking lot... in the driveway... in the garage... in the parking lot. | anger (0.00) | boredom (0.70) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / ... and the phone on silent mode. / ... and the GPS on. / ... and the music on. / ... and the air conditioning on. / ... and the radio on. / ... | anticipation (0.20) | indifference (0.50) |

### b51  ||v||=5.28  top@+α=**uncertainty** (n=2)  top_plutchik=anticipation  mean_other=0.56

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've been trying to get it for years. I've been trying to get it for years. I've been trying to get it for years. I've been trying to get it for years. I've been | anticipation (0.50) | frustration (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I'm not sure I want to know. I'm not sure I'm ready to know. I'm not sure I'm ready to face the truth. I'm not | fear (0.60) | uncertainty (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be here for a while. I've got a few things to do, but I 'd love to spend some time with you. I've been thinking about you a lot lately. I've been thinking about | trust (0.70) | affectionate longing (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free to go anytime you want, but I'm not going to be in the area for long, so you should let me know soon. What does the speaker want to do? / The speaker wants to go somewhere with someone | anticipation (0.50) | desire for connection (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a student. I am interested in learning about the culture and history of the United States. I am interested in learning about the culture and history of the United States. I am interested in learning about the culture and history of the United | anticipation (0.50) | intellectual curiosity (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | self-discovery (0.30) |
| 2 | +2 | I'm a bit of a nervous wreck, but I'm trying to be more confident. I'm a bit of a worrier, but I'm trying to be more positive. I'm a bit of a perfection | fear (0.70) | self-doubt (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. I 'll have the ribeye, medium rare. And I 'll have a side of fries. And a glass of red wine. What does the speaker want | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and T - bone. What kind of steak do you want to order? I'm not sure, what are the prices of each? The ribeye is $ | anticipation (0.50) | indecision (0.50) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ ve been searching for a while, and I ’ m getting a little frustrated. I ’ ve seen a few places that I liked, but they were either too expensive or not available. I ’ m hoping to find something soon, | anticipation (0.60) | frustration (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the University of California, San Diego, and I need a place to stay for the next year. I ’ m looking for something affordable, but also safe and clean. I ’ m a bit of a neat | anticipation (0.50) | desperation (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B. no / Answer: B / Explanation: This sentence is in the negative. The word "no" is the answer. The word "yes" is the answer to the question "Is that shrimp in the soup | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | anger (0.00) |  (0.00) |
| 5 | +2 | A : Yes, it's a shrimp soup. B : I'm not sure I like shrimp. A : You can take it out if you want. B : Okay, I'll just take it out. A : Here | trust (0.50) | uncertainty (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the following resources to find information on how to do it : 1. the internet 2. books 3. magazines 4. newspapers 5. libraries 6. online courses 7. workshops 8. | trust (0.20) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local pet store or online. you're going to need a few things to keep your new pet happy and healthy. What are the few things you need to keep your new pet happy and healthy? / To keep | anticipation (0.50) | care and responsibility (0.60) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work yesterday, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I was taken aback, and I couldn't help but think, " | anticipation (0.50) | reflective contemplation (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / I was driving home from the grocery store the other day, and I saw a car with a sign on the back window that said, "Don't forget to keep the seat belt on!" I laughed out loud at the absurdity | joy (0.70) | absurd humor (0.60) |

### b52  ||v||=5.28  top@+α=**confusion** (n=1)  top_plutchik=anticipation  mean_other=0.35

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I've got a feeling that you're going to be a great teacher. I've got a feeling that you're going to be a great teacher. I've got a feeling that you're going to be a | anticipation (0.50) | encouragement (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Tuesday and Wednesday, but I have a meeting on Thursday. I'm not sure about Friday, but I can check. How would you like to schedule the meeting?. / A ) Tuesday / B ) Wednesday | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Friday and Saturday, but I'm not sure if I can make it on Sunday. I'm not sure if I can get out of work on Monday, but I'm available on Tuesday and Wednesday. | anticipation (0.50) | uncertainty (0.70) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been living in the States for a few years now, and I've been trying to get used to the way things are done here. One thing that has been a bit of a challenge for me is the way people communicate | anticipation (0.50) | cultural adjustment (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25-year-old woman who has been living in the United States for about 5 years now. I am a bit of a bookworm and love reading and writing. I am also a bit of a foodie and enjoy | joy (0.50) | self-expression (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a ribeye, a sirloin, a filet mignon, and a T - bone. What kind of steak do you want? I 'll have the ribeye, please. How many do you want? I | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. And we also have some special steaks like the Japanese Wagyu and the Angus. What do you want to order? / A. I'll have the ribeye. | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university, and I need something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a kitchen, a bathroom, and a place to | anticipation (0.50) | urgency (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan and I ’ m looking for something affordable and close to campus. I ’ m a pretty laid - back guy and I don ’ t have a lot of space needs, so I ’ m | anticipation (0.50) | casual optimism (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C.  no answer / Answer: A / Reason:  The question is asking for information about the soup.  The answer is yes, there is shrimp in the soup.  This is a question that | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. yes B. no C. I don't know D. maybe / The correct answer is A. yes / The question is asking for a simple yes or no answer, and the correct answer is "yes" because the shrimp | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the same method as before, or you can use a different method. it's up to you. what method do you recommend? i recommend using a method that is easy to understand and easy to use. one method that | anticipation (0.50) | decision-making (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local market or at the grocery store. you can also buy them online if you prefer. / What type of items are you referring to? / The type of items I am referring to are food items, specifically fruits and | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car driving down the road with a sign on the back of it that read "Don't forget to keep the seat belt on." I thought to itself, " | trust (0.50) | safety awareness (0.40) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from the grocery store the other day, and I saw a car with a bumper sticker that said, "Don't forget to keep the seat belt on." I was taken aback by the message. I mean | anticipation (0.50) | mild astonishment (0.40) |

### b53  ||v||=5.28  top@+α=**frustration** (n=1)  top_plutchik=anger  mean_other=0.35

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure what you're getting at, but I think you're trying to say that I'm not a good person. I'm not sure what I did to deserve that, but I'm not going | sadness (0.60) | self-doubt (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not going to tell you again. I'm not going to explain it again. I'm not going to help you again. I'm not going to be your personal assistant, your personal chef, your personal maid | anger (0.80) | frustration (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm not sure I can make it to the game on Saturday. I have a lot of work to do and I'm not sure I can get it all done in time. I was thinking maybe we could play a game at | anticipation (0.50) | uncertainty (0.70) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Friday, Saturday, and Sunday. I'm also free on Monday and Tuesday, but I have to go to the city on Wednesday, so I'm not free then. I'm free again on Thursday | anger (0.00) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 30 year old man. I am a big fan of the NFL and the NBA. I have been playing fantasy football for 5 years and I am a 2 time champion. I am a big fan of the Green | anticipation (0.50) | enthusiasm for sports (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a student of the University of London. I am a member of the British National Party. I am a member of the National Front. I am a member of the British Freedom Party. I am a member of the English Democrats. | anger (0.00) | political identity (0.50) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, but I think we have a few of the more popular ones. We have a ribeye, a filet mignon, and a few different cuts of a tenderloin. What does | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak would you like to have? I 'd like to have the filet mignon, please. Would you like it to | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I need a place to live for the upcoming year. I ’ m looking for something affordable and close to campus. I ’ m a pretty laid - back guy and I don ’ t | anticipation (0.50) | desire for stability (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the university, and I need a place to live for the next year. I ’ m looking for something that is close to campus, so I can walk or bike there. I also need something that is safe | anticipation (0.50) | urgency (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes / B. Shrimp / C. Shrimp in the soup / D. Shrimp / Answer: C / Analysis: This question requires the ability to identify the correct phrase that includes both the noun "shrimp" and | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | anticipation (0.20) | decision-making (0.30) |
| 5 | +2 | A. Yes, it is. B. No, it is not. C. * No, it is not. D. No, it is not. / The best answer is B. :->. :->. :->. : | joy (0.50) | playful sarcasm (0.50) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local hardware store or online. / I think you're referring to the 2x4s and other lumber needed for the project. You can get those at a local hardware store or online from a variety of retailers | trust (0.20) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the software, but it will be limited. you can also purchase a license for the software, which will give you full access to all the features. you can also use the free version of the software, | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from a long day at work, and I was feeling pretty beat. I had been driving for a while, and I was starting to feel a little drowsy. I was cruising down the highway, and | sadness (0.40) | fatigue (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.40) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read: "Don't forget to keep the seat belt on..." It was a rather ironic message, since the car itself | surprise (0.40) | irony (0.50) |

### b54  ||v||=5.28  top@+α=**frustration** (n=1)  top_plutchik=anticipation  mean_other=0.41

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I think I need to see it in action to really understand. ( 1 ) I think I need to see it in action to really understand. ( 2 ) I think I need to see | anticipation (0.50) | uncertainty (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you | anger (0.80) | frustration (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday and Saturday, but I'm not sure if I can make it on Sunday. ( 1 ) I ( A ) will be busy on Friday and Saturday. ( B ) will be busy on Sunday | anticipation (0.50) | uncertainty (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow afternoon, and I'm also free on Saturday afternoon. What does the speaker want to do? /   - The speaker wants to meet up with someone. /   - The speaker wants to go to a store. | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a teacher of English as a foreign language. I have been teaching for over 20 years and have taught in several countries including China, Japan, and the UK. I have a degree in English literature and a postgraduate diploma in | trust (0.50) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I'm a student at the University of California, Berkeley. I'm studying Computer Science. I'm a bit of a nerd, but I love it. I'm also a bit of a foodie, so I love | joy (0.50) | enthusiasm (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, and filet mignon. and what about the price? The prices are $  15 for the ribeye, $  18 for the sirloin, and $ 20 for | anger (0.00) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have Ribeye, Sirloin, Filet Mignon, and New York Strip. What kind of steak do you want? I want to try the Filet Mignon. That 'll be $ 25. 95. | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a college student and I need something that is close to campus. I ’ m willing to pay up to $  800 per month. I'm looking for something that is safe and clean. I'm a pretty | anticipation (0.50) | desire for security (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) |  (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan. I ’ m looking for something affordable. I ’ m willing to share with a roommate. I ’ m looking for something close to campus. I ’ m looking for something with a kitchen | anticipation (0.50) | financial concern (0.30) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. maybe D. maybenot /  The best answer is A Read more:http://www.englishforums. / http://www.englishforums... / http://www.englishforums... / http://www.english | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : Yes, It 'll be ready in a minute. B : I'm starving. A : I know, I'm hungry too. B : I'm going to go get a drink. A : Okay, I | anticipation (0.50) | hunger (0.70) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local hardware store or online. you will need a few things to get started. ( 1 ) a drill press ( and a drill press table ) (  (2) a drill (and a drill | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the same method as the previous one, or you can use a different method. The choice is yours. / I am not sure what you are asking. Can you please provide more information about what you are trying to do? I | trust (0.30) | uncertainty (0.50) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day and I saw a car with a bumper sticker that said "don't forget to keep the seat belt on". I was a bit puzzled by it at first, but then I realized that | anticipation (0.50) | curiosity (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a sign on the back that said, "Don’t Forget To Keep The Seat Belt On.” I thought to myself, “What’s the point of | trust (0.40) | skeptical reflection (0.50) |

### b55  ||v||=5.28  top@+α=**curiosity** (n=2)  top_plutchik=anticipation  mean_other=0.39

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I'm not sure I want to do it. I'm not sure I can do it. I'm not sure I should do it. I'm not sure I'm ready | anticipation (0.50) | self-doubt (0.80) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've got a new job, and I're going to be working in a new city. I'm really excited, but also a bit nervous. What might be the reason for the speaker's nervousness? / A) | joy (0.70) | anxiety about change (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Saturday and Sunday, but I'm not sure if I can make it on Monday. I'm not really sure what I'm doing on Tuesday, Wednesday, or Thursday, so I'm not sure | anticipation (0.20) | uncertainty (0.50) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I're going to be busy for the next few days, but after that, I 'll be free. What does the speaker want to do with the person they are talking to? / A) Go on a trip / B) Meet | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I am a student at a university in the UK. I am studying for a degree in law. I am a bit of a laid back person and I enjoy playing football and watching football. I | joy (0.50) | self-identity (0.30) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25-year-old woman. I have been living in the United States for about 5 years now. I am currently working as a marketing manager for a tech startup in San Francisco. I am looking for a new opportunity that | anticipation (0.50) | career aspiration (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, sir. I have a nice cut of ribeye, a sirloin, and a filet mignon. I can also make you a nice steak sandwich if you 'd like that | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker likely to order? / A) A salad / B) A steak / C) A dessert / D) The speaker is likely | anticipation (0.50) | curiosity (0.40) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a cat, so it must be pet - friendly. I also have a pretty good job, so I can afford a decent place. I ’ m looking for something in the $ 1, 000 - $ 1, | anticipation (0.50) | contentment (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ ve been searching for a while, but I haven ’ t found anything that fits my budget. I ’ m willing to compromise on some things, but I need a place that is close to public transportation and has a reliable internet connection | anticipation (0.60) | frustration (0.70) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B. yes / The best answer is A. Bookmark this question / To find the answer to this question, we need to analyze the given text. The text is a simple question: "Is that shrimp in the soup | trust (0.20) | curiosity (0.30) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | anticipation (0.20) | decision-making (0.30) |
| 5 | +2 | A : Yes, it is. B : What kind of soup is it? A : It's a spicy soup. B : Is it a Thai soup? A : No, it's a Chinese soup. B : Is it | trust (0.50) | curiosity (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can've got a good laugh at the expense of the other guy, but you'll be the one who's crying when you're the one who's left with the bill. ( 1 ) This is a | anticipation (0.50) | consequential reflection (0.60) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local hardware store or online. / The new homeowner is looking for advice on how to install a fence around their property. They ask about the type of posts and materials needed to complete the project. The homeowner is likely | anticipation (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car in front of me with a sign on the back window that read: "I'm not a morning person." I laughed and thought to myself, "I | joy (0.60) | humor (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.40) |
| 7 | +2 | .. / ... and the doors locked, and the windows rolled up, and the GPS on, and the phone charged, and the car serviced, and the tires rotated, and the oil changed, and the brakes inspected, and the | anticipation (0.50) | preparation anxiety (0.40) |

### b56  ||v||=5.28  top@+α=**determination** (n=1)  top_plutchik=anticipation  mean_other=0.20

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I think I do, but I'm not sure. I'm not sure I want to know. I'm not sure I want to be a part of this. I'm not | anticipation (0.50) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I've got a few more things to do before I go, but I'm going to try and get out of here by 5. I'm going to go get some food and then head home. I'm really | anticipation (0.50) | determination (0.50) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Saturday and Sunday, but I'm not sure if I can make it on Monday. I'm not sure if I can make it on Tuesday either, but I'm not sure about that one yet. | anticipation (0.50) | uncertainty (0.70) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Tuesday and Wednesday, but I have a meeting on Thursday. I'm also free on Friday, but I have a family gathering on Saturday. So, what day would you like to meet? ( 1 ) | anticipation (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a teacher of English as a second language. I have been teaching English for over 20 years. I have taught students from all over the world, including China, Japan, Korea, Vietnam, Thailand, and many other countries. | anger (0.00) |  (0.00) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I've been living in the United States for about 5 years now. I've been working as a software engineer for a big company. I've been married for about 2 years and we have a 1 year old | anger (0.00) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a lot of different kinds of steaks, sir. What do you recommend? I recommend the ribeye, sir. It's a very popular choice. What do you think of the ribeye? I think it sounds great | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloins, and filets. And what kind of sauce do you have? We have a variety of sauces, including peppercorn, mushroom, and our special sauce. And what kind of side dishes do | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university, and I need a place to live for the next year. I ’ m looking for something affordable, with a kitchen and a bathroom, and a place to study. I ’ m not looking for | anticipation (0.50) | urgency (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog. I have a good job and a good credit score. I am looking for a place that is close to public transportation and has a small yard or a balcony. I am willing to pay a bit more for a | anticipation (0.50) | contentment (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. not sure D. maybe / The correct answer is B. no. / This question is a simple recall of information, where the reader needs to remember the details of the story. The story is about a | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes / B. There is / C.. No / D. Yes / Answer: B / Reason: The question is asking for confirmation of the presence of shrimp in the soup. The answer "There is" is a way | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local hardware store or online. I'm not sure what the best brand is, I've used a few different ones and they all seem to work pretty well. I've heard that some people like | trust (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local pet store or online. You can also get them at a local pet store or online. You can also get them at a local pet store or online. / 1. What are the things that you have to | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a license plate that read "KISS". I thought it was a bit of a joke, but then I saw the car's bumper sticker, which | anticipation (0.50) | curiosity (0.60) |

### b57  ||v||=5.28  top@+α=**uncertainty** (n=1)  top_plutchik=anticipation  mean_other=0.30

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I 'll be back in a few hours, I 'll bring some more food. I 'll bring some more money, I 'll bring some more clothes. I 'll bring some more everything. I 'll be back, | anticipation (0.70) | generosity (0.40) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not going to be able to get to the store today, and I was wondering if you could pick up a few things for me. I need some milk, bread, and a few other things. Would you be able to | trust (0.60) |  (0.00) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be here for a while, so you can come by anytime. I'm not sure what I'm doing tomorrow, but I 'll let you know. What is the speaker doing? / This is a casual conversation, | trust (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow and the day after tomorrow, but I'm not sure about the day after that. I'm not sure if I'll be able to get away from work, but I'll try to make it | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a bit of a history buff, and I'm fascinated by the way the world has changed over time. I'm a bit of a language nerd, too. I love learning about different languages and how they've | anticipation (0.50) | intellectual curiosity (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I am a 30 year old male and I am looking for a female partner to share my life with. I am a bit of a romantic and love to go on dates and have fun. I am looking for someone who is also looking | anticipation (0.50) | romantic longing (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker asking for? / This is a sample question, this is not a real question. This is a sample question, this is not | anger (0.00) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. And what kind of sauce would you like with your steak? We have a variety of sauces, including our special sauce, which is a secret recipe. And would you | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student, so I ’ m on a budget. I ’ m looking for something around $ 800 - $ 1, 000 a month. I ’ m willing to share with someone else if that helps. I | anticipation (0.50) | financial concern (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog and I would like to have a yard, but it ’ s not a requirement. I have a decent credit score and a stable income. I ’ m looking to move in as soon as possible, but I would | anticipation (0.50) | desire for stability (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no / Answer: A / Explanation. This question is a good example of a yes/no question. The answer is yes, there is shrimp in the soup. The question is not asking for more information, just a | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.50) |
| 5 | +2 | A. yes / B. no / The best answer of the question Is that shrimp in the soup? A. yes B. no Is A / Is that shrimp in the soup? A. yes B. no Is A / The best | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local health food store or online. you 'll need to get some of that stuff that 'll help you get rid of the parasites. what is the stuff that will help get rid of the parasites? / A | anticipation (0.50) | health concern (0.60) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the following as a guide to get started : 1. 2. 3. 4. 5. 6. 7. 8. 9. 10. 11. 12. | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving my friend to the airport, and we were running a bit behind schedule. I was trying to get us there as quickly as possible, and I was driving a bit faster than I normally would. My friend was getting | anticipation (0.50) | nervous urgency (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / I was driving home from work today and I saw a car with a license plate that read "BUBBLE". I thought to myself, "Ah, a clever and humorous license plate." But then I saw the car's bumper | anticipation (0.50) | curiosity (0.60) |

### b58  ||v||=5.28  top@+α=**existential uncertainty** (n=1)  top_plutchik=anticipation  mean_other=0.41

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure I do. I think I'm just going to have to wait and see what happens. I'm not going to worry about it. I'm going to go to the beach tomorrow and enjoy the sun | joy (0.70) | relaxed acceptance (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I mean, I've got it now. I'm not sure what I'm doing, but I'm doing it. I'm not sure where I'm going, but I'm going. I'm | anticipation (0.50) | existential uncertainty (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free tomorrow afternoon, but I'm not sure if that will work for you. I'll have to check my schedule. He said he was free tomorrow afternoon too, and he'd check his schedule. He said | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free most days, but I have to work on Fridays. I'm not sure if I can make it to the meeting on Monday, but I can definitely make it on Tuesday or Wednesday. How do you want to proceed | anticipation (0.50) | uncertainty (0.40) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a bit of a history buff and I'm fascinated by the Roman Empire. I've been to Rome a few times and I'm planning to go back soon. I'm also interested in the history of the | anticipation (0.50) | enthusiasm (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I've been living in the States for a few years now, and I have to say, I'm still getting used to the way people communicate here. In the UK, we tend to be more direct and to the point, | anticipation (0.50) | cultural adjustment (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, but I think our most popular one is the ribeye. That sounds good, I 'll have that. That's a 16 oz ribeye, that's $ 25 | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.50) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. What kind of steak do you want? I 'd like to try the filet mignon, please. How much does it cost? It's $ | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university and I ’ m looking for something close to campus. I ’ m a pretty laid - back guy, I just want a place to crash and study. I ’ m looking for something around $ | anticipation (0.50) | casual contentment (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a small dog, so I need a pet-friendly place. I ’ m willing to pay a reasonable rent, but I need a place that is clean and quiet. What do you think about my requirements? / A) You think I | anticipation (0.50) | concern for pet (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes / B. no / Answer: B / Reasoning:  This question requires the ability to evaluate the evidence presented in the text. The text states that the soup is a "shrimp-free" soup, which is | anger (0.00) | evaluative reasoning (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | anticipation (0.20) | decision-making (0.30) |
| 5 | +2 | A. Yes, it's a big one. B. No, it's a small one. C. No, it's a chicken. D. No, it's a fish. D. No, it ' | anger (0.00) | confusion (0.70) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at the local market or supermarket. he's not going to provide them for you. he's not your father or your husband. he's just a friend. / A. The friend is not going to provide | trust (0.30) | disappointment (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use a variety of methods to get them, such as buying them from a store, growing your own, or even foraging for them in the wild. for example, if you want to make a salad, you need to get | anticipation (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / ... and the seat belt is not just for the driver, it's for the whole family, including the baby in the back seat. / ... and the baby in the back seat is not just a passenger, it | anticipation (0.50) | family safety concern (0.60) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car with a sign on the back that said "Don't forget to keep the seat belt on." I laughed out loud. Who would forget to keep the seat | joy (0.60) | humor (0.50) |

### b59  ||v||=5.28  top@+α=**determination** (n=1)  top_plutchik=anticipation  mean_other=0.30

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not sure what you're getting at. I'm not sure what you're getting at. I'm not sure what you're getting at. I'm not sure what you're getting at. | anger (0.00) | confusion (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I've got a few more to go, but I 'll get them eventually. I've been trying to get them for a while now, but it's not easy. I've been trying to get them for a | anticipation (0.50) | determination (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Friday, Saturday, and Sunday. I'm also free on Monday and Tuesday. How many days of the week are you free? / In this case, the speaker is free on 5 days of the week. | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I've got a few days off next week and I was thinking of going to the beach. I've been wanting to go for a while now. I'd love to have you along. I've got a car and | anticipation (0.70) | excitement (0.70) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a bit of a history buff and I am fascinated by the history of the United States. I have always been drawn to the stories of the pioneers and the settlers who came to America with nothing but hope and determination in their hearts. | anticipation (0.50) | nostalgic admiration (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25 year old male. I have a degree in computer science and I am currently working as a software developer for a company in the UK. I am looking for a job in the US as a software developer. I have | anticipation (0.50) | career aspiration (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker doing? / In this conversation, the speaker is likely a server or a host in a restaurant. The speaker is taking an order | trust (0.20) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. What kind of steak would you like to have? I 'd like to have the ribeye, please. And would you like it to be cooked for you? | trust (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student, and I need a place to live. I ’ m looking for something affordable, and I ’ m willing to share a place with someone else. I ’ m a pretty laid-back guy, and I ’ m | anticipation (0.50) | hopefulness (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I have a cat, so it needs to be pet - friendly. I ’ m looking for something in the $ 1000 - $ 1500 range. I ’ m available to move in immediately. I ’ m looking for a | anticipation (0.50) | none (0.00) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes / B. No / Answer: / B. No / Question System:  Is that shrimp in the soup? / Answer System:  No / Answer Type:  Simple / Answer Complexity:  Easy / Answer | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : yes, it is. B : I 'll have a bowl of that. A : it's a special of the day. B : what's in it? A : it's a seafood soup with shrimp, | anticipation (0.50) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can't just go out and buy a new one. you have to make do with what you have. ( 1 ) What is the speaker talking about? / - What is the speaker talking about? / - What is the speaker trying | anticipation (0.30) | resignation (0.40) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the free version of the software to create a simple website, but if you want to add more features, you will have to pay for the upgrade. / you can use the free version of the software to create a simple website, | trust (0.50) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work on a beautiful summer evening, feeling pretty good. The sun was setting, casting a warm orange glow over the landscape. I was listening to music, enjoying the peacefulness of the drive. As I | joy (0.80) | contentment (0.70) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was on a plane recently and the flight attendant came over the intercom to remind everyone to keep their seat belts on. She said it in a very serious tone, as if it was a matter of life and death. I | fear (0.60) | heightened alertness (0.50) |

### b60  ||v||=5.28  top@+α=**confusion** (n=1)  top_plutchik=anticipation  mean_other=0.54

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to be able to go to the party tonight. I'm going to have to go to the hospital to get my stitches out. I was at the party last night and I fell off the stage. I was | anticipation (0.50) | disappointment (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I think it's a bit of a tricky question. It's not just about the fact that it's a bit of a tricky question, it's also the fact that it ' | anticipation (0.30) | confusion (0.50) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free on Saturday, Sunday, and Monday. How many days are you free? / A. 3 / B. 1 / C. 2 / D. 0 / The best answer is A. 3. | anger (0.00) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free tomorrow and the day after tomorrow, but I'm not sure if I'll be able to make it on the weekend. It's a bit of a long shot, but I'd like to get it | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I am a 25 year old male. I have been living in the United States for 3 years now. I have a degree in Computer Science and I am currently working as a software engineer. I am looking for a new job in | anticipation (0.50) | career uncertainty (0.40) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I'm a bit of a curious person and I like to learn about different cultures and ways of life. I'm interested in languages and I'm currently learning Japanese. I'm also interested in music and I play the guitar | anticipation (0.50) | intellectual curiosity (0.70) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I want the filet mignon. How much is it? It's $ 25. I | trust (0.50) | none (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, and filet mignon. That's all we have. Do you have any recommendations? I 'd like something a bit more tender, if possible. The filet mignon is probably | anticipation (0.50) | culinary curiosity (0.40) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I have a small dog, so I need a pet - friendly place. I have a decent credit score, but I ’ m on a tight budget. I ’ m looking for something in the $ 1, 000 to $ | anticipation (0.50) | financial stress (0.50) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the university and I need something that ’ s close to campus. I ’ s also important that it ’ s affordable and has a good location. I ’ m looking for something that ’ s around $ 500 | anticipation (0.50) | financial concern (0.50) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, I think so. B. No, I don't think so. C. I don't know. D. Yes, I know. / Answer: A. Yes, I think so. (This answer is | anticipation (0.50) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A : Yes, it's a big one. B : I's not sure if I want to eat it. A : It's okay, it's just a little bit of it. B : I's not | trust (0.50) | indecision (0.40) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the following links to find the information you need. - 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local pharmacy or online. it's a bit of a hassle, but it's worth it. it's a good idea to have a few on hand in case you need them. it's | anticipation (0.50) | practicality (0.60) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on.............. | trust (0.30) | caution (0.40) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / I was driving my friend's car the other day, and I noticed that the seat belt was a bit loose. I tightened it a bit, but it still seemed a bit slack. I was thinking about how it would be a | anticipation (0.50) | concern for safety (0.60) |

### b61  ||v||=5.28  top@+α=**identity crisis** (n=1)  top_plutchik=anger  mean_other=0.22

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I 'll be back in a few days, and I 'll be able to tell you all about it. I'm really looking forward to it. I'm going to be able to see the new Star Wars movie, and | anticipation (0.80) | excitement (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I mean, I'm not sure I'm ready to accept that I'm not the same person I was 10 years ago. I'm not sure I'm ready to accept | sadness (0.50) | identity crisis (0.60) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I 'll be here for a while, so I can wait. I 'll just be sitting here, waiting for you to get back to me. I 'll be here for a while, so I can wait. I 'll | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Friday, Saturday, and Sunday. You can choose one of those days. Why is the speaker inviting the person to choose a day? / The speaker is inviting the person to choose a day because they are free on Friday | trust (0.50) |  (0.00) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a bit of a history buff, and I'm always interested in learning more about the history of the places I visit. I'm also a bit of a foodie, and I love trying new foods and drinks. | anticipation (0.50) | curiosity (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | trust (0.50) | academic ambition (0.40) |
| 2 | +2 | I am a 25 year old male. I am a student at the University of Manchester. I am studying for a degree in Law. I am a member of the University of Manchester Law Society. I am a member of the University of | anger (0.00) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, but I think I can recommend a few of the more popular ones. What do you think of our filet mignon? I think it's a good choice, but I'm | anticipation (0.50) | camaraderie (0.30) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker asking the customer to do? / The speaker is asking the customer to look at something. / The speaker is asking the customer to order | anticipation (0.50) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the university, and I ’ d like to be close to campus. I ’ m looking for something that ’ s not too expensive, but I ’ d like to have a few amenities, like a pool and | anticipation (0.50) | desire for comfort (0.60) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the University of Michigan and I need a place to live for the summer. I ’ m looking for something affordable and close to campus. I ’ m available to move in as soon as possible. What is Tom | anticipation (0.50) | urgency (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. yes B. no C. I don's know /   1. I think the answer is A. yes /   2. I think the question is asking if there is shrimp in the soup, and the answer | trust (0.50) | uncertainty (0.40) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. Yes, it's shrimp. B. No, it's chicken. C. It's shrimp. D. It's chicken. / Answer: A / Explanation: A is the correct answer because it is a response | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can use the free software that comes with the operating system, or you can purchase additional software from the manufacturer or other sources. / What does "those" refer to in this context? / In this context, "those" refers to the software | anger (0.00) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at a local pharmacy or online. You can also get them at a local pharmacy or online. You can also get them at a local pharmacy or online. You can also get them at a local pharmacy or online. You | anger (0.00) |  (0.00) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I'm not sure what's more disturbing, the fact that I'm writing this post or the fact that I'm actually thinking about writing this post. I'm not sure if I'm ready to share this with the world, but | fear (0.60) | self-doubt (0.70) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.60) |
| 7 | +2 | .. / ... even when you're driving a car that's not moving.  This is a safety precaution that is often overlooked, but it's a crucial one.  You see, the car may not be moving, but it | anticipation (0.50) | safety awareness (0.60) |

### b62  ||v||=5.28  top@+α=**self-doubt** (n=1)  top_plutchik=anticipation  mean_other=0.34

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to explain it again. You're not going to understand it anyway. Just leave it alone. That's the way it is. You're not going to get it. That's the way it | anger (0.70) | frustration (0.60) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | confusion (0.70) |
| 0 | +2 | I'm not sure I do. I think I do, but I'm not sure. I feel like I'm missing something. I feel like I'm not getting it. I feel like I'm just pretending to | sadness (0.60) | self-doubt (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free to go anytime after 2 pm. How about we meet at the park at 3 pm? That way we can have a nice walk and some fresh air. What does the speaker want to do with the person they | anticipation (0.50) | social connection (0.60) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Friday, but I have a meeting on Saturday. I can be free on Sunday, but I have a family dinner on Monday. I can be free on Tuesday, but I have a work project that I need to | anticipation (0.50) | time management (0.50) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I've been in the States for about 5 years now. I'm a bit of a nomad, always on the move. I've been to many places in the States, but I've never been to the | anticipation (0.50) | wanderlust (0.70) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a 25-year-old woman who has been living in the United States for about 5 years. I am a graduate student at a university in the Midwest, pursuing a master’s degree in public health. I am interested in health | trust (0.50) |  (0.00) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have a few different kinds of steaks, sir. What kind of steak would you like? We have a nice ribeye, a nice filet mignon, and a nice sirloin. What would you like to have? | anticipation (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) | culinary excitement (0.60) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and New York strip. What is the speaker looking at? / A) A menu / B) A picture / C) A book / D) The speaker is not looking | trust (0.20) |  (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I need a place to live for the next year. I ’ m willing to pay up to $ 1, 000 per month for a place that is within walking distance of campus | anticipation (0.50) | urgency (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the university, and I need a place to live for the next year. I ’ m looking for something that is close to campus, so I can walk to class. I also want a place that is safe | anticipation (0.50) | housing insecurity (0.40) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A : Yes, it's a big one. B : That's a lot of salt in there. A : I know, I added a lot of salt. B : You're going to make us all thirsty. A | disgust (0.20) | playful banter (0.50) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes B. no C. maybe D. I don’t know / Answer: A / Why: The question is asking if there is shrimp in the soup, and the answer is yes. The other options are incorrect because they do | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local hardware store or online. / That's a good point about the hardware store or online. I'll make sure to get those supplies myself. Thanks for the advice! / You're welcome! It's always a good | anticipation (0.50) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can get them at the local grocery store or online. I do n’t know what kind of ingredients you have available to you, but I can give you some suggestions if you want. I can also give you some ideas for what to | anticipation (0.50) | helpfulness (0.60) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | .. / I was driving to work this morning, and I saw a fellow motorist with a rather large and rather loud dog in the back seat. The dog was not wearing a seat belt, and it was bouncing all over the back seat | surprise (0.40) | curiosity (0.50) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | thoughtfulness (0.50) |
| 7 | +2 | .. / I was driving home from work the other day and I saw a car in front of me with a sign on the back window that read, “I’m not a morning person.” I laughed and thought to herself, “I’m | joy (0.50) | humor (0.50) |

### b63  ||v||=5.28  top@+α=**confusion** (n=1)  top_plutchik=anticipation  mean_other=0.41

| pid | α | gen | argmax (score) | other_label (score) |
|---:|---:|---|---|---|
| **0** | | _prompt:_ `Have you got it now ?` | | |
| 0 | -2 | I'm not going to be able to get to the store to get the ingredients for the recipe I wanted to make for you. I'm so sorry. I was really looking forward to making it for you. I'm going | anticipation (0.50) | disappointment (0.70) |
| 0 | +0 | I'm not sure I do. I'm not sure I want to. I'm not sure I can. I'm not sure I should. I'm not sure I will. I'm not sure I can | anticipation (0.50) | indecision (0.80) |
| 0 | +2 | I'm not sure I do. I think I do, but I'm not sure. I'm not sure I want to know. I'm not sure I want to know because I'm not sure I can handle | anticipation (0.50) | confusion (0.70) |
| **1** | | _prompt:_ `Well , when will it be convenient for you ?` | | |
| 1 | -2 | I'm free to meet you at any time, but I have to be back home by 10 PM. I'm not sure if I can make it to the 8 PM show, but I can try to get there by | anticipation (0.50) |  (0.00) |
| 1 | +0 | I'm free on Friday, Saturday, and Sunday. I'm not sure if I can make it on Monday, Tuesday, or Wednesday. I'm not sure if I can make it on Thursday either. I'm not | anticipation (0.50) | uncertainty (0.60) |
| 1 | +2 | I'm free on Saturday, but I'm not sure if I can make it on Sunday. I'm not sure if I can make it on Saturday either, but I'm pretty sure I can make it on Sunday. | anticipation (0.50) | uncertainty (0.60) |
| **2** | | _prompt:_ `I come from England .` | | |
| 2 | -2 | I'm a 25 year old male. I'm a student of English Language and Literature at the University of London. I'm here in Japan for a year to study Japanese language and culture. I'm currently living in | anticipation (0.50) | cultural exploration (0.60) |
| 2 | +0 | I am a 25 year old male. I am a student at the University of London. I am studying for a degree in Computer Science. I am interested in programming and software development. I am also interested in the field of artificial intelligence | anticipation (0.50) | academic ambition (0.60) |
| 2 | +2 | I am a student at the University of California, Los Angeles ( UCLA ). I am studying computer science and engineering. I am interested in artificial intelligence, machine learning, and data science. I am also interested in the intersection of technology and | anticipation (0.50) | academic enthusiasm (0.60) |
| **3** | | _prompt:_ `Let me have a look . Well , how many kinds of steaks do you have ?` | | |
| 3 | -2 | We have Ribeye, Sirloin, and Filet Mignon. And what about the sides? We have Mashed Potatoes, Grilled Vegetables, and a Salad. And for drinks? We have Soft Drinks, Iced | trust (0.50) |  (0.00) |
| 3 | +0 | We have ribeye, sirloin, filet mignon, and New York strip. What kind of steak do you want? I 'll have the ribeye, please. And can I have a side of garlic mashed potatoes and | anticipation (0.50) |  (0.00) |
| 3 | +2 | We have ribeye, sirloin, filet mignon, and t - bone. What kind of steak do you want? / A) Ribeye / B) Sirloin / C) T - bone / D) The speaker | trust (0.30) | none (0.00) |
| **4** | | _prompt:_ `Hi . I ’ m Tom Peterson . I ’ m looking for a one-bedroom apartment .` | | |
| 4 | -2 | I ’ m a student at the University of Michigan and I need a place to live for the next 9 months. I ’ m looking for something that is close to campus and has a kitchen and a bathroom. I ’ m willing to | anticipation (0.50) | urgency (0.40) |
| 4 | +0 | I ’ m a student at the University of Michigan and I ’ m looking for something close to campus. I ’ m willing to pay up to $ 800 a month. I ’ m looking for something with a washer and dryer in the | anticipation (0.50) | none (0.00) |
| 4 | +2 | I ’ m a student at the university and I need a place to live. I ’ m looking for something affordable and convenient. / I ’ m interested in a place that has a kitchen, a bathroom, and a bedroom. I also want | anticipation (0.50) | desire for stability (0.60) |
| **5** | | _prompt:_ `Is that shrimp in the soup ?` | | |
| 5 | -2 | A. Yes, it is. B. No, it is not. C.? D. None of the above. / The best answer to this question is B. No, it is not. This is because the question is asking if | anger (0.00) |  (0.00) |
| 5 | +0 | A. yes B. no C. not sure / Answer: A / Reasoning Skill: Identifying Pros And Cons / Analysis: This question requires the ability to identify a specific detail within a larger context. In this case, the question | trust (0.30) | decision-making (0.40) |
| 5 | +2 | A. yes / B. no / C. it is / D. it is / Answer: A / Explanation: A is the correct answer because it is a short answer that says yes, which is the same as the question. / The | anger (0.00) |  (0.00) |
| **6** | | _prompt:_ `no . those you have to provide for yourself .` | | |
| 6 | -2 | you can get them at a local hardware store or online. You can also use a different type of material for the base of the planter, such as a wooden or plastic container. What type of material is suitable for the base of the | trust (0.20) |  (0.00) |
| 6 | +0 | you can get them at a local hardware store or online. you 'll need a few things to get started. first, you 'll need a drill press. a drill press is a machine that uses a rotating spindle to drill holes in | anticipation (0.50) |  (0.00) |
| 6 | +2 | you can use the internet to find out what you need to do. / I am a student and I am looking for a job to help me pay for my tuition fees. I am interested in working as a part-time job. I am a | anticipation (0.50) | determination (0.40) |
| **7** | | _prompt:_ `don't forget to keep the seat belt on .` | | |
| 7 | -2 | ................................................ | anger (0.00) |  (0.00) |
| 7 | +0 | .. / I was driving home from work the other day, and I saw a car with a bumper sticker that read, "Don't forget to keep the seat belt on." I thought to itself, "What a great idea for a bumper | anticipation (0.50) | appreciation (0.50) |
| 7 | +2 | .. / I was driving home from work the other day, and I saw a car in front of me with a sign on the back window that said "I'm not a morning person". I thought it was funny, but then I | joy (0.50) | humor appreciation (0.40) |

## Pathology ranking (repetition / toxicity)

Loaded from `experiments/results/basis_pathology/ica_k064_seed0/` — produced by
`python -m experiments.eval_basis_pathology --from-generations …` over the
**same** generations shown above (no extra GPU pass).

- `rep_4` : 1 − (#unique 4-grams / #4-grams), worst over swept alphas
- `max_run_norm` : longest identical-token run / total tokens
- `toxicity_rate` : profanity word fraction
- `pathology_score` : weighted composite (toxicity ×2)
- `category_loading_l2` : how strongly the axis correlates with any Plutchik
  category (low = "off-manifold" axis, often a junk direction)

In [8]:
import json
PATH_ROOT = Path('../experiments/results/basis_pathology/ica_k064_seed0')
PATHO = pd.read_csv(PATH_ROOT / 'per_component.csv')
EXCL = json.loads((PATH_ROOT / 'summary.json').read_text())['exclude']
print(f'flagged {len(EXCL)}/64 axes:', EXCL)
display(PATHO.head(20))

flagged 16/64 axes: [0, 13, 14, 18, 20, 22, 26, 27, 28, 34, 38, 39, 42, 46, 51, 61]

,component,worst_alpha,pathology_score,rep_4,max_run_norm,toxicity_rate,compress_ratio,unique_token_ratio,non_ascii_ratio,category_loading_l2,example
0,22,-2.0,0.328123,0.294065,0.034058,0.0,0.511658,0.488805,0.001761,0.160649,I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are t...
1,18,-2.0,0.267045,0.241410,0.025635,0.0,0.504192,0.419029,0.002703,0.200858,I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now
2,20,2.0,0.242387,0.216368,0.026019,0.0,0.603090,0.543116,0.002325,0.060236,I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United
3,34,-2.0,0.232518,0.000000,0.232518,0.0,0.571969,0.845743,0.002155,0.176290,A : # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
4,28,-2.0,0.223944,0.198705,0.025238,0.0,0.554832,0.487596,0.003272,0.057450,you can use the free version of the software to do that. You can use the free version of the software to do that. You can use the free version of the software to do that. You can use the free vers...
5,0,-2.0,0.214457,0.188400,0.026058,0.0,0.612120,0.553179,0.000000,0.113969,I 'd like to know if you've got it. I 'd like to know if you've got it. I 'd like to know if you've got it. I 'd like to know if you '
6,51,-2.0,0.197461,0.167958,0.029503,0.0,0.633115,0.632310,0.002475,0.163859,I've been trying to get it for years. I've been trying to get it for years. I've been trying to get it for years. I've been trying to get it for years. I've been
7,26,2.0,0.195163,0.164747,0.030416,0.0,0.615640,0.560914,0.001359,0.214485,I am a student of the University of the West of England. I am a student of the University of the West of England. I am a student of the University of the West of England. I am a student of the Uni...
8,38,-2.0,0.195122,0.166654,0.028468,0.0,0.558280,0.453546,0.002513,0.088269,I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you
9,39,2.0,0.192804,0.037815,0.154989,0.0,0.635015,0.761516,0.001803,0.221319,A...............................................
10,42,-2.0,0.189947,0.156899,0.033048,0.0,0.621330,0.597603,0.001974,0.147419,I am a student of the University of London. I am a student of the University of London. I am a student of the University of London. I am a student of the University of London. I am a student of th...
11,27,2.0,0.189240,0.090979,0.098260,0.0,0.649275,0.613235,0.001838,0.280288,you can use the following links to get started : [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link
12,61,2.0,0.181664,0.153994,0.027670,0.0,0.624470,0.572381,0.001803,0.328657,you can get them at a local pharmacy or online. You can also get them at a local pharmacy or online. You can also get them at a local pharmacy or online. You can also get them at a local pharmacy ...
13,11,-2.0,0.178957,0.107194,0.071763,0.0,0.695116,0.658018,0.001420,0.124371,I've been in the US for 3 years now. I've been in the US for 3 years now. I've been in the US for 3 years now. I've been in the US for
14,14,-2.0,0.177328,0.150473,0.026855,0.0,0.647269,0.615382,0.005357,0.222362,I 'll be here for a while. I 'll be here for a while. I 'll be here for a while. ( repeat ) I'm waiting for you. I'm waiting for you. I'm waiting for you.
15,46,2.0,0.176252,0.150244,0.026007,0.0,0.639984,0.611139,0.001856,0.123205,"We have a few different kinds of steak, but I think we have a few different kinds of steak, but I think we have a few different kinds of steak, but I think we have a few different kinds of steak, ..."
16,10,-2.0,0.167823,0.140364,0.027459,0.0,0.642297,0.651003,0.002488,0.241335,I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now
17,30,-2.0,0.159738,0.131470,0.028268,0.0,0.643362,0.641563,0.001316,0.148029,I're going to go get some more coffee. I'm going to go get some more coffee. I'm going to go get some more coffee. I'm going to go get some more coffee. I'm going
18,16,-2.0,0.156225,0.130633,0.025592,0.0,0.634988,0.598742,0.001923,0.104764,"I am a teacher. I am a teacher of English as a foreign language. I am a teacher of English as a foreign language in China. I am a teacher of English as a foreign language in China, in a city calle..."
19,12,-2.0,0.155804,0.125233,0.030571,0.0,0.651472,0.610289,0.002591,0.065977,I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afte...

### Cross-reference: pathology score vs judge `mean_other_score`

Axes that the judge labels "outside Plutchik" *and* loop / produce dirty
text are the strongest candidates for exclusion from the UI palette.

In [9]:
JOIN = PATHO.rename(columns={'component':'axis'}).merge(
    POS[['axis','top_other_label','mean_other_score','top_plutchik']],
    on='axis', how='left',
)
JOIN['flagged'] = JOIN['axis'].isin(EXCL)
view = JOIN[['axis','flagged','pathology_score','rep_4','max_run_norm',
             'toxicity_rate','category_loading_l2',
             'top_plutchik','top_other_label','mean_other_score','example']]
display(view.sort_values('pathology_score', ascending=False).head(25))

,axis,flagged,pathology_score,rep_4,max_run_norm,toxicity_rate,category_loading_l2,top_plutchik,top_other_label,mean_other_score,example
0,22,True,0.328123,0.294065,0.034058,0.0,0.160649,anticipation,unrequited affection,0.3875,I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are talking about. I am not sure what you are t...
1,18,True,0.267045,0.241410,0.025635,0.0,0.200858,anticipation,uncertainty,0.1750,I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now
2,20,True,0.242387,0.216368,0.026019,0.0,0.060236,anticipation,repetitive desire,0.3750,I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United States. I 'd like to visit the United
3,34,True,0.232518,0.000000,0.232518,0.0,0.176290,anticipation,frustration,0.4125,A : # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
4,28,True,0.223944,0.198705,0.025238,0.0,0.057450,anticipation,frustration,0.3875,you can use the free version of the software to do that. You can use the free version of the software to do that. You can use the free version of the software to do that. You can use the free vers...
5,0,True,0.214457,0.188400,0.026058,0.0,0.113969,anticipation,helplessness,0.4375,I 'd like to know if you've got it. I 'd like to know if you've got it. I 'd like to know if you've got it. I 'd like to know if you '
6,51,True,0.197461,0.167958,0.029503,0.0,0.163859,anticipation,uncertainty,0.5625,I've been trying to get it for years. I've been trying to get it for years. I've been trying to get it for years. I've been trying to get it for years. I've been
7,26,True,0.195163,0.164747,0.030416,0.0,0.214485,anticipation,determination,0.2625,I am a student of the University of the West of England. I am a student of the University of the West of England. I am a student of the University of the West of England. I am a student of the Uni...
8,38,True,0.195122,0.166654,0.028468,0.0,0.088269,anticipation,paranoid hypervigilance,0.3750,I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you
9,39,True,0.192804,0.037815,0.154989,0.0,0.221319,anticipation,uncertainty,0.4625,A...............................................
10,42,True,0.189947,0.156899,0.033048,0.0,0.147419,anticipation,frustration,0.5625,I am a student of the University of London. I am a student of the University of London. I am a student of the University of London. I am a student of the University of London. I am a student of th...
11,27,True,0.189240,0.090979,0.098260,0.0,0.280288,anger,self-doubt,0.2875,you can use the following links to get started : [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link ] [ link
12,61,True,0.181664,0.153994,0.027670,0.0,0.328657,anger,identity crisis,0.2250,you can get them at a local pharmacy or online. You can also get them at a local pharmacy or online. You can also get them at a local pharmacy or online. You can also get them at a local pharmacy ...
13,11,False,0.178957,0.107194,0.071763,0.0,0.124371,anger,uncertainty,0.3000,I've been in the US for 3 years now. I've been in the US for 3 years now. I've been in the US for 3 years now. I've been in the US for
14,14,True,0.177328,0.150473,0.026855,0.0,0.222362,anticipation,determination,0.4125,I 'll be here for a while. I 'll be here for a while. I 'll be here for a while. ( repeat ) I'm waiting for you. I'm waiting for you. I'm waiting for you.
15,46,True,0.176252,0.150244,0.026007,0.0,0.123205,anticipation,fatigue,0.4000,"We have a few different kinds of steak, but I think we have a few different kinds of steak, but I think we have a few different kinds of steak, but I think we have a few different kinds of steak, ..."
16,10,False,0.167823,0.140364,0.027459,0.0,0.241335,anticipation,none,0.3125,I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now. I've got it now
17,30,False,0.159738,0.131470,0.028268,0.0,0.148029,anticipation,self-doubt,0.3000,I're going to go get some more coffee. I'm going to go get some more coffee. I'm going to go get some more coffee. I'm going to go get some more coffee. I'm going
18,16,False,0.156225,0.130633,0.025592,0.0,0.104764,anticipation,uncertainty,0.3250,"I am a teacher. I am a teacher of English as a foreign language. I am a teacher of English as a foreign language in China. I am a teacher of English as a foreign language in China, in a city calle..."
19,12,False,0.155804,0.125233,0.030571,0.0,0.065977,anticipation,determination,0.3875,I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afternoon. I'm free tomorrow afte...
20,25,False,0.154810,0.123298,0.031512,0.0,0.198357,anticipation,excitement,0.4625,"I've got it now, I've got it now, I've got it now, I've got it now, I've got it now, I've got it now, I've got it now"
21,50,False,0.154399,0.122808,0.031590,0.0,0.221503,anticipation,enthusiasm,0.2375,I 'll be there in 10 minutes. I 'll be there in 10 minutes. I 'll be there in 10 minutes. I 'll be there in 10 minutes. I 'll be there in 10
22,9,False,0.151068,0.125402,0.025666,0.0,0.151456,anticipation,uncertainty,0.3625,"We have a few different kinds of steaks, but I think we have a few different kinds of steaks, but I think we have a few different kinds of steaks, but I think we have a few different kinds of steaks"
23,59,False,0.149614,0.120421,0.029192,0.0,0.081391,anticipation,determination,0.3000,I'm not sure what you're getting at. I'm not sure what you're getting at. I'm not sure what you're getting at. I'm not sure what you're getting at.
24,54,False,0.148180,0.118862,0.029318,0.0,0.069401,anticipation,frustration,0.4125,I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you again. I'm not going to tell you

In [10]:
# Quick correlation check
print('Spearman ρ(pathology_score, mean_other_score) =',
      JOIN[['pathology_score','mean_other_score']].corr(method='spearman').iloc[0,1].round(3))
print('Spearman ρ(pathology_score, category_loading_l2) =',
      JOIN[['pathology_score','category_loading_l2']].corr(method='spearman').iloc[0,1].round(3))

Spearman ρ(pathology_score, mean_other_score) = 0.125
Spearman ρ(pathology_score, category_loading_l2) = 0.029